### ISSUE TITLE
Onboard Elyse V.

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#131]
# Instructions for the issue creator:
 - [X] Assign yourself and the new person joining to this GitHub issue
 - [x] Add the new person to the 18F-TLC google group. This will invite them to all the meetings!
 - [X] Welcome them in #18f-da-team (For example, :wave: @person joining! We're looking forward to you joining us next week!)
 - [X] Add them to the DA GitHub team

# For the person onboarding
- [x] Review our [README](https://github.com/18F/delivery-assurance#readme)
- [x] Review our [Charter](https://github.com/18F/delivery-assurance/blob/main/docs/charter.md)
- [x] Meet with one of the team leads to:
     - [x] Learn about the current priorities, share where you’re at and what skills you’d like to flex while you’re a part of the group! 
     - [x] Review the work **On-Deck** in our [project board](https://github.com/orgs/18F/projects/41) for anything that interests you.
     - [x] Choose a place for you to start by assigning a ticket in the On-Deck, or help someone out with something In-Progress or In-Review
 - [x] Document any questions that come up during your first week in our [questions board](https://docs.google.com/spreadsheets/d/1J8cAcuE2zgpIFSJx_mKOjNmAcQGeYtQbz2vkTuqGI4U/edit#gid=1340104815)

**Comment by evoeges** [comment]
README and charter links both go to the charter.

**Comment by MelissaBraxton** [comment]
Thanks for catching that! I'll fix the template. 

But here's the README in the meantime: https://github.com/18F/delivery-assurance#readme
