### ISSUE TITLE
Facilitate reflection for 18F Account Management Team on 4/27 from 1-2pm ET

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#162]
### A description of the work
Facilitate reflection for 18F Account Management Team on 4/27 from 1-2pm ET. 

18F Account Management would like to establish team "standards" so that project teams understand what having an account manager on a project team entails. Currently, each account manager (AM) runs their projects a bit differently and it can be confusing as to what teams should expect and what AMs have autonomy over. 

Outcome: an understanding between AMs on what is expected on all projects, what can/should be done on certain projects and what is always optional. 

The AMs would like to use their weekly team sync for this and @rrefoy is available/interested in helping prep ahead of the facilitation, like with pre populating a mural with items from the Account Management handbook (as options for us to prioritize) and have the ability to create our own items.

### Point of contact on this issue
@rrefoy and @Erica-Perkins 

**Billable?**
- [ ] Yes
- [x] No

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
This is schedule for 4/27 from 1-2pm.

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?
2-3 hours. 1 hour for planning, 1 for running the reflection, 1 for reflection synthesis. 

### Acceptance Criteria

- [x] Reflection is planned with input from @rrefoy 
- [x] Reflection is facilitated on 4/27 from 1-2pm
- [x] Reflection is synthesized

**Comment by annepetersen** [comment]
This is currently scheduled during TLC crew's retro time. Could we move one or the other so everyone can participate in that?

**Comment by rrefoy** [comment]
It would be very challenging to move the AM sync.

**Comment by alexbielen** [comment]
@rrefoy Our retro time has moved to 5/4 so we are clear to take this on. 

Tagging in @evoeges who will be taking this on!

**Comment by SelenaJV** [comment]
I saw this issue pop up and think it's a great idea for the AMs to get on the same page about this. Reminder that this[ Role Inventory](https://github.com/18F/staffing/wiki/18F-Role-inventory) was created a few months ago and may be a helpful input to the retro conversation and/or something that needs to get updated after the retro.

**Comment by evoeges** [comment]
This ticket is now blocked- the AM team was missing a few people on Thursday 4/27 and voted to reschedule the workshop for May 11. Everything is prepped in [this mural](https://app.mural.co/t/gsa6/m/gsa6/1682612161123/20f9b82b0e0023d6407fef3aaf9d854156d20fb9?sender=u6d9f4b887bb1c0c352c50732), so I'll pass this off to someone else if I'm not on TLC crew at that point.

**Comment by MelissaBraxton** [comment]
Thanks @evoeges ! We can close this out, since you've completed the tasks and acceptance criteria that were in scope for the issue. @abrouilette will carry it forward from here.

**Comment by evoeges** [comment]
@MelissaBraxton,  @abrouilette and I met today and because I haven't been staffed yet it seems to make the most sense for me to continue on with this ticket and run the workshop on May 11. Should I reopen this ticket...?

**Comment by MelissaBraxton** [comment]
Yes, I'll reopen the issue. Apologies for any confusion!

**Comment by evoeges** [comment]
This workshop was facilitated so I'm closing this ticket! The synthesis work for this is a bit larger than a regular reflection, so I opened [a new ticket here](https://github.com/18F/TLC-crew/issues/239) for that work.
