### ISSUE TITLE
#18-tlc-crew-alerts

### ISSUE THREAD

**Issue by abrouilette** [18F/TLC-crew#167]
Could we please have a channel, a la #18f-staffing-alerts, to import these issues into Slack? 

(I am amenable to "No, because....")

### Point of contact on this issue
@abrouilette 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human _who knows how to do this. I think Christa Hartsock set up the staffing one; I have no idea how difficult this is or is not._
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
I am of the impression this might be something an engineer could knock off in maybe an hour max.  If I am considerably wrong (highly plausible) it might change my desire to have this. 

### Acceptance Criteria

- [ ] What does "done" look like?

As an 18F person who has enough to look at already, I would like to be able to scan what's going on without going issue to issue in the repo so I can try to keep in tune with the TLC crew without having to routinely read another freakin' repo.

**Comment by MelissaBraxton** [comment]
@alexbielen  - This seems fine to me. What are your thoughts?

**Comment by alexbielen** [comment]
We are taking this on. I'm putting it into in-progress and @geekygirlsarah is implementing it.

**Comment by geekygirlsarah** [comment]
Created channel #18f-tlc-crew-alerts yesterday, and added the GitHub bot to post issues from:
[18F/18f.gsa.gov](https://github.com/18F/18f.gsa.gov)
[18F/accessibility](https://github.com/18F/accessibility)
[18F/agile](https://github.com/18F/agile)
[18F/blog-drafts](https://github.com/18F/blog-drafts)
[18F/brand](https://github.com/18F/brand)
[18F/content-guide](https://github.com/18F/content-guide)
[18F/derisking-gov-tech](https://github.com/18F/derisking-gov-tech)
[18F/development-guide](https://github.com/18F/development-guide)
[18F/eng-hiring](https://github.com/18F/eng-hiring)
[18F/handbook](https://github.com/18F/handbook)
[18F/methods](https://github.com/18F/methods)
[18F/product-guide](https://github.com/18F/product-guide)
[18F/TLC-crew](https://github.com/18F/TLC-crew)
[18F/tock](https://github.com/18F/tock)
[18F/uswds-jekyll](https://github.com/18F/uswds-jekyll)
[18F/ux-guide](https://github.com/18F/ux-guide)

This is not the most ideal as it means if another repo is added to the GitHub board, it also has to be added to this channel separately. I tried tying it into the workflow that adds issues from other repos into this board, but it appears to need special permissions that would have to get added by the Slack admins. (I can pursue this but haven't at this moment.)  I also pursued getting a bot token to have it post new issues in there with a GitHub Action, but that also requires installing an app and would have to get permissions from Slack admins. (Again, can pursue, just a complex hurdle.) 

I'll put this in review for the moment.

**Comment by geekygirlsarah** [comment]
I've requested access to a Slack app that would allow me to post messages in a GitHub action after talking to Greg. 

This is now blocked until that approval goes through.

**Comment by alexbielen** [comment]
I think for now I'm happy with just seeing TLC-Crew alerts. Anything more than that is too much investment for this issue. If you could roll back the subscriptions for the other repos and keep it TLC-Crew alerts only I think that we can call this done.

**Comment by geekygirlsarah** [comment]
The channel now only shows changes to issues in the `18f/tlc-crew` repo. (This may not note changes on the project board, which would need a different thing set up.) This sounds like it would be done now.

I can't cancel the Slack app request, so if/when it gets approved, we can revisit adding this into the GitHub Actions workflow if you want. Otherwise there's no harm in having the app anyway for future projects.
