### ISSUE TITLE
Onboard Michael King

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#174]
# Instructions for the issue creator:
 - [x] Assign yourself and the new person joining to this GitHub issue
 - [x] Add the new person to the 18F-TLC google group. This will invite them to all the meetings!
 - [x] Welcome them in #18f-tlc-crew (For example, :wave: @person joining! We're looking forward to you joining us next week!)
 - [x] Add them to the DA GitHub team

# For the person onboarding
- [x] Fill out this brief [onboarding questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSc_1tPO9jLd0SipCm5ot7bPUj8o-UhWdduGpIBVUHbRN6ntbg/viewform?usp=sf_link)
- [x] Review our [README](https://github.com/18F/delivery-assurance#readme)
- [x] Review our [Charter](https://github.com/18F/delivery-assurance/blob/main/docs/charter.md)
- [x] Meet with one of the team leads to:
     - [x] Learn about the current priorities, share where you’re at and what skills you’d like to flex while you’re a part of the group! 
    -  [x] Review the work in **prioritized** on our [project board](https://github.com/orgs/18F/projects/41) for anything that interests you.
    -  [x] Choose a place for you to start by assigning a ticket in **prioritized**, or help someone out with something In-Progress or In-Review
 - [ ] Document any questions that come up during your first week in our [questions board](https://docs.google.com/spreadsheets/d/1J8cAcuE2zgpIFSJx_mKOjNmAcQGeYtQbz2vkTuqGI4U/edit#gid=1340104815)

**Comment by kingcomma** [comment]
@alexbielen Any qualms with me moving this to done? I'll continue to add questions to the questions board if/when they come up.

**Comment by alexbielen** [comment]
No qualms! Move it on over
