### ISSUE TITLE
update DA/TLC ReadMe

### ISSUE THREAD

**Issue by annepetersen** [18F/TLC-crew#184]
### A description of the work
Our ReadMe needs to be updated: first items I see are updating the Team Lead listing and making the change from DA to TLC throughout, but I bet there are other changes

### Point of contact on this issue
@MelissaBraxton or @alexbielen, I would assume

### Reproduction steps (if necessary)
Read the [ReadMe](https://github.com/18F/delivery-assurance#readme) and make updates on items that have changed

**Billable?**

No

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] What does "done" look like?

A new TLC member (or anyone who's interested in how TLC operates) can read accurate information and take action that works for both them and the (rest of) TLC crew.

**Comment by MelissaBraxton** [comment]
Updates are here: https://github.com/18F/delivery-assurance/pull/190

**Comment by alexbielen** [comment]
Done!
