### ISSUE TITLE
Facilitate final project reflection for USTP project

### ISSUE THREAD

**Issue by christophermather** [18F/TLC-crew#186]
### A description of the work
A clear and concise description of what the work entails.
Our engagement with USTP concludes this week and we'd like someone to facilitate an end-of-project reflection for our internal 18F team this Thursday (5/4) at 11am.

### Point of contact on this issue
Who can we follow-up with if we have questions?
Chris Mather

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [x] Yes
- [ ] No
If yes, tock code: 1616

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?
4-5 hours, depending on how long planning and synthesis take. 1 hour total for facilitation

### Acceptance Criteria

- [ ] What does "done" look like?
As a team member for the USTP engagement, I can review a synthesized reflection document with helpful insights and information that can potentially be shared with leadership or the rest of 18F.

ex: As an 18F staff member who is going on parental leave, I can navigate to my
latest Tock reporting period and choose billing line #1810 by filtering by
number or "extended OOO"

**Comment by jskinne3** [comment]
Created [synthesized document](https://docs.google.com/document/d/1rDtQ9VsblTkf6U0_z8lZ56WwigHImJ6DTMUXMMRwljY/) (summary followed by full text); awaiting review in #ustp-post-award-mgmt Slack channel
