### ISSUE TITLE
[HOLD UNTIL 5/23 Increment Planning] Facilitate a project reflection for TMF

### ISSUE THREAD

**Issue by rrefoy** [18F/TLC-crew#188]
### A description of the work
@AnitaYCheng is wrapping up her work with TMF the week of 5/8 so a project reflection either at the end of the week or the week of 5/15.

### Point of contact on this issue
Who can we follow-up with if we have questions? 
@rrefoy 

**Billable?**

- [x] Yes
- [ ] No
If yes, tock code: 1798

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?
3-4 hours

### Acceptance Criteria

- [ ] What does "done" look like?

A summarized project reflection posted in #project-reflections

**Comment by MelissaBraxton** [comment]
@rrefoy  - We'll be able to assign someone to this on 5/9 so they can get it done by 5/19.

**Comment by alexbielen** [comment]
@evoeges to lead and @jasnakai to shadow

**Comment by rrefoy** [comment]
We've had a slight staffing change and @AnitaYCheng will be 25% allocated to TMF until 5/26/23, so ideally this reflection would be pushed to the week of 5/30. I'm sorry y'all, @alexbielen and @MelissaBraxton, I forgot to follow up here late last week when we decided this. Does that change the staffing assignments?

**Comment by alexbielen** [comment]
Gotcha! Thanks for the heads up. We'll move this back into planning for our next increment. 

cc: @evoeges @jasnakai I'll remove you from this for now.

**Comment by rrefoy** [comment]
Unrelatedly, this is a billable engagement where a person shadowing could bill to the project.

**Comment by alexbielen** [comment]
@evoeges to lead and @HannaSChang to shadow.

**Comment by rrefoy** [comment]
@MelissaBraxton and @alexbielen can we get a different facilitator if Elyse and Anita's schedules don't align?

**Comment by MelissaBraxton** [comment]
Hey there @rrefoy and @AnitaYCheng  - Is next week ok for this reflection? We'd heard this week might be off the table anyway due to Anita's jury duty schedule. If we are really set on this Friday as the reflection date, then we can see about finding another facilitator, but our capacity is very low this week.

**Comment by rrefoy** [comment]
I think it's okay to push to next week then.

**Comment by MelissaBraxton** [comment]
First task is to find out whether this is doable week of 6/12 bc/ @AnitaYCheng 's jury duty schedule

**Comment by MelissaBraxton** [comment]
I'm going to carry this forward for @HannaSChang who's no longer on the crew. 

Remaining steps:

- [ ] Confirm Anita has no edits after she reviews when she's back from jury duty. 
- [ ] Post to reflections channel
- [ ] Upload to Airtable
