### ISSUE TITLE
Write a proposal for how TLC crew can help maximize organizational learning from project reflections

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#196]
### A description of the work
The scope of this work os a proposal for how the TLC crew might help the organization learn from project reflections. 

Things the proposal should address: 
 - what percentage of crew’s time that should be spent on project reflections
 - how to optimize TLC crew assignments to optimize for their conducting reflections
 - processes to support meta analyses across reflections
 - processes for communicating learnings back to the rest of organization

### Point of contact on this issue
@kfoley-18F, @alexbielen, @MelissaBraxton   

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [x] We have a document that describes a proposal that lays out processes for the TLC crew supporting meta analysis of project reflection data and how learnings from these analyses will be communicated back to the rest of the organization.

**Comment by alexbielen** [comment]
@jduss4 and @jasnakai to lead this. 

Tag in @annepetersen for review!

**Comment by annepetersen** [comment]
The [triple-loop learning model from Guides & Methods (slides 51-55 here](https://docs.google.com/presentation/d/1HV4bQ3RURAXTFeI03ewWH9pGyFX7POZueNpoUFPVOx0/edit#slide=id.g1c600a657ba_1_64)) may help

**Comment by jduss4** [comment]
[Proposal](https://docs.google.com/document/d/1EVqNl2khVBGQpzgU46SnzJosNfjpkUjZNAX6OvtsHes/edit#) sent to Alex and Melissa for review

**Comment by MelissaBraxton** [comment]
This is looking really good! 

I'd like to revise the format a bit to organize the info under "what, why, how, who, and when" headers. It's a format that some folks at 18F learned in the art of alignment training, and I think having it in that structure will help us move forward in aligning others on executing this proposal.

I added some comments re: sections that map to those headers, because you basically have all the right content! (aside from explicit sections for when and how, I think).  

Also, here are a few example proposals using that structure: 

https://docs.google.com/document/d/1YMkd9kcdHedz1CHlaKJlGSRllXXAlmIk2lSanskXeQg/edit#

https://docs.google.com/document/d/1yTUC1maBxoVzjZL7B3VQyY_w-HIwNRIO6J6_AtefPsk/edit#

**Comment by jduss4** [comment]
Okay, we will have to revisit when and how!  I think we should be able to do this, though, no problem!

**Comment by jduss4** [comment]
See #235 for part 2 of the work
