### ISSUE TITLE
De-risking prototype for Astro static site generator

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#206]
### A description of the work
This work is part of Epic #176 which tracks the prototyping step in 18F's [decision process](https://docs.google.com/document/d/16DMVEq0-O3mgz6rxJCGYu3sdDSwePGBmLA94wyAf_ho/edit#heading=h.j5b4edppf0q5) for a new static site generator. 

This ticket deals with building a "de-risking prototype" for the [Astro static site generator. ](https://astro.build/). This prototype is meant to test the [criteria](https://docs.google.com/document/d/16DMVEq0-O3mgz6rxJCGYu3sdDSwePGBmLA94wyAf_ho/edit#heading=h.dbuhuf33m8ub) outlined in the decision record.

**Point of contact on this issue**
@beechnut 

**Billable?**

- [x] No

**Skills needed**

- [x] Engineering

**Timeline**
Does this need to happen in the next two weeks?

- [x] No

How much time do you anticipate this work taking?
~40 hours

### Acceptance Criteria
**DevSecOps**

- [x] Create repository to store results of prototype
- [x] Deploy to Cloud.gov Pages
- [x] Containerize a local environment with Docker
- [x] Evaluate and document build times for 200 pages of content (the size of the Handbook, used as reference)
- [x] Integrate with GitHub Actions
- [x] Integrate with automated CI tools (linter, pa11y)

**Maintenance**

- [x] Add a dependency and document how they are tracked and upgraded 
- [x] Test USWDS integration

**Features**

- [x] Test and document approach to multilingual support (localization / internationalization aka i18n)
- [x] Test that SSG supports markdown code blocks
- [x] Test support for asset management for whole site (styles, images, fonts, scripts) as well as individual pages (images, videos, scripts)
- [x] Test for flexible page layouts / templates (can support some unique styling, for example the 18F Methods)
- [x] Test support for embedding video content

**Other**

- [x] Document results of the prototype and share with @beechnut

**Comment by julialeague** [comment]
Created prototype repository: https://github.com/18F/guides-and-methods-astro

**Comment by julialeague** [comment]
The [Google Sheet tracking the decision criteria](https://docs.google.com/spreadsheets/d/1EDDbnT4nHPj4MlH9CcLoZxO2sBVzT4YI3UEzbewxZs8) has been filled out completely for Astro, based on my research and actions in the prototype repo. 

I'm moving this issue's status to In Review to give @beechnut and @alexbielen @MelissaBraxton and TLC Crew a chance to review the work against the acceptance criteria. Thanks!

**Comment by beechnut** [comment]
@julialeague prototyped and researched of existing work in Astro to complete of all the de-risking criteria. Looks good!
