### ISSUE TITLE
De-risking prototype for Hugo static site generator

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#207]
### A description of the work
This work is part of Epic #176 which tracks the prototyping step in 18F's [decision process](https://docs.google.com/document/d/16DMVEq0-O3mgz6rxJCGYu3sdDSwePGBmLA94wyAf_ho/edit#heading=h.j5b4edppf0q5) for a new static site generator. 

This ticket deals with building a "de-risking prototype" for the [Hugo static site generator. ](https://gohugo.io/). This prototype is meant to test the [criteria](https://docs.google.com/document/d/16DMVEq0-O3mgz6rxJCGYu3sdDSwePGBmLA94wyAf_ho/edit#heading=h.dbuhuf33m8ub) outlined in the decision record.

Unlike #206 the Astro issue, 18F previously tested Hugo during the Guides and Methods (G&M) project. The team evaluated a number of important criteria and documented them in https://github.com/18F/guides-and-methods-hugo

This work will involve understanding the G&M Hugo Prototype and evaluating if the prototype tested the [relevant criteria.](https://docs.google.com/document/d/16DMVEq0-O3mgz6rxJCGYu3sdDSwePGBmLA94wyAf_ho/edit#heading=h.dbuhuf33m8ub) Where there are gaps, further testing will be necessary. 

**Point of contact on this issue**
@beechnut 

**Billable?**

- [x] No

**Skills needed**

- [x] Engineering

**Timeline**
Does this need to happen in the next two weeks?

- [x] No

How much time do you anticipate this work taking?
~20 hours

### Acceptance Criteria

**Context Building**

- [x] Read through the [G&M Hugo repository](https://github.com/18F/guides-and-methods-hugo)
- [X] Read through [supporting documentation](https://docs.google.com/document/d/1xVLZvDuIKHAGpkecTJrF3wg1jWhprOAjXpiq9n4yxps/edit#heading=h.6u22hetmshpb)
- [X] Identify which criteria below still need to be tested (Added to @beechnut's [spreadsheet](https://docs.google.com/spreadsheets/d/1EDDbnT4nHPj4MlH9CcLoZxO2sBVzT4YI3UEzbewxZs8/edit#gid=259457433))

**DevSecOps**

- [X] Create repository to store results of prototype ([Hugo Guides](https://github.com/18F/guides-and-methods-hugo), [Digital.gov](https://github.com/GSA/digitalgov.gov), [NIST Hugo theme](https://github.com/usnistgov/hugo-uswds), [NIST Hugo docs/demo](https://github.com/usnistgov/hugo-uswds-docs))
- [X] Deploy to Cloud.gov Pages ([Hugo guides build](https://pages.cloud.gov/sites/1253/builds))
- [X] Containerize a local environment with Docker (Docker Hub's [Hugo image](https://hub.docker.com/r/klakegg/hugo))
- [X] Evaluate and document build times for 200 pages of content (the size of the Handbook, used as reference) (306 pages took [1s in Cloud.gov](https://pages.cloud.gov/sites/1253/builds/286312/logs), digital.gov takes [20s for >9800 pages](https://gsa-tts.slack.com/archives/C057815V70C/p1684517562613539)
- [x] Integrate with GitHub Actions ([G&M's Actions](https://github.com/18F/guides-and-methods-hugo/actions/runs/5005377096/jobs/8969250791))
- [x] Integrate with automated CI tools (linter, pa11y) (digital.gov has a [pa11y prototype](https://github.com/GSA/digitalgov.gov), but personally Matt, Julia, and I couldn't get G&M to run it)

**Maintenance**

- [X] Add a dependency and document how they are tracked and upgraded (digital.gov uses [npm to install USWDS](https://github.com/GSA/digitalgov.gov/blob/main/package.json#L30), Go has a package manager but we didn't have a package to add)
- [X] Test USWDS integration (see above)

**Features**

- [X] Test and document approach to multilingual support (localization / internationalization aka i18n) ([G&M has i18n](https://github.com/18F/guides-and-methods-hugo/tree/main/content))
- [X] Test that SSG supports markdown code blocks ([MD in G&M](https://github.com/18F/guides-and-methods-hugo/tree/main/content/en))
- [X] Test support for asset management for whole site (styles, images, fonts, scripts) as well as individual pages (images, videos, scripts) (see notes in [spreadsheet](https://docs.google.com/spreadsheets/d/1EDDbnT4nHPj4MlH9CcLoZxO2sBVzT4YI3UEzbewxZs8/edit#gid=259457433))
- [X] Test for flexible page layouts / templates (can support some unique styling, for example the 18F Methods) (G&M has [different layouts](https://federalist-1d60e1c6-edfd-4ed3-b30a-e8a2a15b5cae.sites.pages.cloud.gov/site/18f/guides-and-methods-hugo/section5/)
- [X] Test support for embedding video content ([G&M](https://federalist-1d60e1c6-edfd-4ed3-b30a-e8a2a15b5cae.sites.pages.cloud.gov/site/18f/guides-and-methods-hugo/section6/page-with-images/))

**Other**

- [X] Document results of the prototype and share with @beechnut

**Comment by geekygirlsarah** [comment]
In review for @beechnut and @alexbielen

**Comment by beechnut** [comment]
@geekygirlsarah's research and prototyping led to the completion of all the de-risking criteria.
