### ISSUE TITLE
De-risking prototype for the Eleventy static site generator

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#208]
### A description of the work
This work is part of Epic #176 which tracks the prototyping step in 18F's [decision process](https://docs.google.com/document/d/16DMVEq0-O3mgz6rxJCGYu3sdDSwePGBmLA94wyAf_ho/edit#heading=h.j5b4edppf0q5) for a new static site generator. 

This ticket deals with building a "de-risking prototype" for the [Eleventy static site generator. ](https://www.11ty.dev/). This prototype is meant to test the [criteria](https://docs.google.com/document/d/16DMVEq0-O3mgz6rxJCGYu3sdDSwePGBmLA94wyAf_ho/edit#heading=h.dbuhuf33m8ub) outlined in the decision record.

Unlike #206 the Astro issue, 18F has previous experience with  Eleventy. The TTS Handbook was re-written in Eleventy. 

This work will involve understanding how the TTS Handbook uses Eleventy and evaluating if that implementation meets the [relevant criteria.](https://docs.google.com/document/d/16DMVEq0-O3mgz6rxJCGYu3sdDSwePGBmLA94wyAf_ho/edit#heading=h.dbuhuf33m8ub) Where there are gaps, further testing will be necessary. 

**Point of contact on this issue**
@beechnut 

**Billable?**

- [x] No

**Skills needed**

- [x] Engineering

**Timeline**
Does this need to happen in the next two weeks?

- [x] No

How much time do you anticipate this work taking?
~10 hours

### Acceptance Criteria

**Context Building**

- [x] Understand the FAC team and [TTS Handbook](https://github.com/18F/handbook)'s use of Eleventy 
- [x] Identify which criteria below still need to be tested

**DevSecOps**

- [X] Create repository to store results of prototype ([Handbook](https://github.com/18F/handbook), [FAC-Frontend](https://github.com/GSA-TTS/FAC-Frontend), [FAC-transition-site](https://github.com/GSA-TTS/FAC-transition-site))
- [x] Deploy to Cloud.gov Pages (see [Handbook](https://pages.cloud.gov/sites/21/builds), [FAC-Frontend](https://pages.cloud.gov/sites/1162/builds))
- [x] Containerize a local environment with Docker ([FAC-transition-site](https://github.com/GSA-TTS/FAC-transition-site))
- [x] Evaluate and document build times for 200 pages of content (the size of the Handbook, used as reference) ([Handbook](https://github.com/18F/handbook/actions/workflows/pull-request.yml) seems to average 2.5 min with 1.5 min actual 11ty build)
- [x] Integrate with GitHub Actions ([Handbook](https://github.com/18F/handbook/blob/main/.github/workflows/pull-request.yml), [FAC-Frontend](https://github.com/GSA-TTS/FAC-Frontend/blob/main/.github/workflows/main.yml))
- [x] Integrate with automated CI tools (linter, pa11y) ([FAC-frontend](https://github.com/GSA-TTS/FAC-Frontend/blob/main/.github/workflows/main.yml))

**Maintenance**

- [x] Add a dependency and document how they are tracked and upgraded ([Handbook](https://github.com/18F/handbook/blob/main/package.json), [FAC-Frontend](https://github.com/GSA-TTS/FAC-Frontend/blob/main/package.json), [FAC-transition-site](https://github.com/GSA-TTS/FAC-transition-site/blob/main/package.json))
- [x] Test USWDS integration ([Handbook](https://github.com/18F/handbook), [FAC-Frontend](https://github.com/GSA-TTS/FAC-Frontend), [FAC-transition-site](https://github.com/GSA-TTS/FAC-transition-site))

**Features**

- [x] Test and document approach to multilingual support (localization / internationalization aka i18n) [eleventy-plugin-i18n-demo](https://github.com/adamduncan/eleventy-plugin-i18n-demo/tree/master/src) with folders for content in languages, _data containing key/values,  _data/i18n containing config)
- [x] Test that SSG supports markdown code blocks ([Handbook](https://github.com/18F/handbook/tree/main/pages), see hundreds of pages, [FAC-transition-site](https://github.com/GSA-TTS/FAC-transition-site/tree/main/src))
- [x] Test support for asset management for whole site (styles, images, fonts, scripts) as well as individual pages (images, videos, scripts) ([Handbook](https://github.com/18F/handbook/blob/main/.eleventy.js), [FAC-Frontend](https://github.com/GSA-TTS/FAC-Frontend/blob/main/.eleventy.js))
- [x] Test for flexible page layouts / templates (can support some unique styling, for example the 18F Methods) (see [11ty Layouts](https://www.11ty.dev/docs/layouts/))
- [x] Test support for embedding video content (concept exists through existing shortcodes on [Handbook](https://github.com/18F/handbook/blob/main/config/shortcodes.js))

**Other**

- [x] Document results of the prototype and share with @beechnut (shared on their [spreadsheet](https://docs.google.com/spreadsheets/d/1EDDbnT4nHPj4MlH9CcLoZxO2sBVzT4YI3UEzbewxZs8/edit#gid=259457433))

**Comment by geekygirlsarah** [comment]
Tagging @alexbielen and @beechnut for review

**Comment by beechnut** [comment]
@geekygirlsarah's research and prototyping led to the completion of all the de-risking criteria.
