### ISSUE TITLE
Failcon presentation: things to know about IAAs and SOWs

### ISSUE THREAD

**Issue by cjhskippy** [18F/TLC-crew#209]
### A description of the work

Provide some scaffolding for new project leads for by sharing what I wish I'd known about interagency agreements, statements of work, and the responsibilities of project leads

### Point of contact on this issue
@cjhskippy

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?

4 days

### Acceptance Criteria

- [x] Deck supporting a failcon presentation
- [x] Delivery of failcon presentation
- [ ] Suggestions for onboarding new project leads
- [ ] Recommendations on systems 18F can develop to support teams to meet terms of agreements
- [ ] Share out suggestions + recommendations within 18F internal channels

**Comment by pburkholder** [comment]
What's a FailCon presentation?

**Comment by MelissaBraxton** [comment]
@cjhskippy I think this is now done? 

@pburkholder  - At last week's team coffee, we had folks present about work fails so that others can learn from them! Highly recommend watching the recording!
https://www.nytimes.com/2014/11/09/business/wearing-your-failures-on-your-sleeve.html

**Comment by cjhskippy** [comment]
@MelissaBraxton Yes! I'm open to / interested in adapting any of that into project lead training materials if desired, but that's an @adunkman decision. Happy to close this and consider "make any of that reusable" future work.
