### ISSUE TITLE
Strategy for Writing Lab requests

### ISSUE THREAD

**Issue by colinmurphy01** [18F/TLC-crew#21]
### A description of the work

Related to #20, the writing lab / writing editors takes on requests for editing assistance through slack (mainly in helpwanted and microrequests). They have a unique process for managing those requests and assigning that work but it has gone quiet with the high turnover the content team has experienced. 

A proposed hypothesis for how the DA Team and the Writing Lab could support one another would be:
- DA Team can act as a drafting partner with a SME on externally facing documentation: blog posts, guide content, etc.
- When ready, the writing lab acts an editor for plain language and clarity

DA Team will not take on requests for:
- Project materials, those will be directed towards Writing Lab
- Anything outside of 18F

This ticket will clarify and propose an intake process for those requests, how they're managed by the DA Team and writing lab.

Convo Notes:
- [Initial convo with Amanda](https://docs.google.com/document/d/1BcGjZjQs0IBm-LHaGp0Jj9LOBE9bUsAGuAYcoup05R0/edit#heading=h.mga6juxwcenk)
- [Meeting with Content Guild](https://docs.google.com/document/d/1BcGjZjQs0IBm-LHaGp0Jj9LOBE9bUsAGuAYcoup05R0/edit#heading=h.kxxgnk2vdmx9)

**Point of contact on this issue**
@amandacostello @michelle-rago @colinmurphy01 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
2 weeks

### Acceptance Criteria

- [x] It's clear where anyone from 18F can request help on content, such as blog post ideas, methods, guides content
- [x] It's clear where anyone from 18F can request help on project deliverables
- [x] It's clear where anyone outside of 18F can request help on content
- [x] There is a process for managing those requests in a timely manner
- [x] There is a process for recruiting for writing lab support

**Comment by colinmurphy01** [comment]
Attending Content Guild on Friday 3/10 to discuss

**Comment by annepetersen** [comment]
[Notes from Content Guild meeting](https://docs.google.com/document/d/1BcGjZjQs0IBm-LHaGp0Jj9LOBE9bUsAGuAYcoup05R0/edit#heading=h.kxxgnk2vdmx9) 

From Content Guild's point-of-view, their proposed governance (basically a re-statement of what @colinmurphy01 has above, but covering project work):

- Anyone in TTS can be part of the editor pool to take on requests (editors from rest of TTS field requests from the rest of TTS: to this point have just not addressed them, but may have to be more explicit)
- 18F maintains the workflow oversight for 18F work
- (Re-)Create and maintain an on-call calendar, making sure those requests get answered, matching work to person
- Process stays in Slack for now
- Refresh list of people that will be pinged by @writing-editors, including all the new 18F content staff
- Try to shepherd that work through

DA team may want to propose process for internal 18F work (check for qualified DA team members first, for example) like blog posts, website updates, non-project content

**Comment by annepetersen** [comment]
Semi-blocked, waiting on the content guild to update the @writing-editors Slack group

**Comment by michelle-rago** [comment]
These things are done.
- (Re-)Create and maintain an on-call calendar, making sure those requests get answered, matching work to person
- Refresh list of people that will be pinged by @writing-editors, including all the new 18F content staff
    - We added new folks to the list and removed some. There are probably still some on the list who won't pick up assignments but I think that's okay for now.

**Comment by melchoyce** [comment]
What needs to happen next to move this issue forward?

**Comment by annepetersen** [comment]
I think the acceptance criteria are complete with these changes to the @writing-editors group in Slack, so I just checked them off, but I'm not sure we validated the original hypothesis, or otherwise made a call on how the DA team relates here.

> A proposed hypothesis for how the DA Team and the Writing Lab could support one another would be:
> 
> - DA Team can act as a drafting partner with a SME on externally facing documentation: blog posts, guide content, etc.
> - When ready, the writing lab acts an editor for plain language and clarity
>
> DA Team will not take on requests for:
> 
> - Project materials, those will be directed towards Writing Lab
> - Anything outside of 18F
> 
> This ticket will clarify and propose an intake process for those requests, how they're managed by the DA Team and writing lab.

@MelissaBraxton, maybe you could compare this to the [pull request you just made](https://github.com/18F/delivery-assurance/pull/118) describing what work is in scope for DA and make sure that documentation covers the above hypothesis sufficiently?

**Comment by MelissaBraxton** [comment]
This sounds great to me! I added this to [PR118](https://github.com/18F/delivery-assurance/pull/118). Once 118 is merged, we can call this done.
