### ISSUE TITLE
Understand how TLC Crew can contribute to Google Analytics Migration

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#215]
### A description of the work
#115 mentions Google Analytics data exporting. This is part of a larger initiative from the Digital Council. This issue will figure out if and how TLC Crew contributes to that larger initiative. 

### Point of contact on this issue
@alexbielen and @MelissaBraxton 

**Billable?**

- [ ] Yes
- [X] No

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] We've documented our responsibility to contribute to GA migration and any follow on work as new issues.

**Comment by annepetersen** [comment]
[Some background](https://docs.google.com/document/d/14vzfqkFuqJ6J2hVLx6RNGJ_qz0YbeI4Ml7wA1S6pn6w/edit#heading=h.jmjn81mtfaop) and [first efforts to export data](https://docs.google.com/document/d/1PtzgTKDxfQnvt59IY7PoH45KLmDXBQr5lVC8Dr8WavA/edit#heading=h.c5c4fi6plvug) along with [the backups in question](https://drive.google.com/drive/folders/1bhegdf0tp1Lr8I6ZLGE7rPjzNOA-sXUl) through the analytics guild, just starting to be rebooted

**Comment by jduss4** [comment]
Just spoke with @gbinal and @Leighdiddy about their work on the analytics migration. They are 40% through exporting data from 18F websites they know about and are on track to finish before the July 1st migration.

At this time, they do not require any assistance.

Minor note: if anyone during the history of 18F has started a new GA account for a website, Gray and Leigh may not be aware of it and it will not be archived, so let them know if you are aware of any they should look into!

**Comment by MelissaBraxton** [comment]
Sounds good! My read on this is that (1) we can call this issue done, and (2) nothing is needed from 18F to support the GA migration.
