### ISSUE TITLE
Approach reflection: Document learnings on forking open source applications 

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#221]
### A description of the work
Ryan Ahearn recently ended his work on the TTS Benefits Studio's Notify project. The Notify project forked other open source applications and we would like to document what was learned from this approach.

### Point of contact on this issue
@rahearn 
@alexbielen 

**Billable?**

- [ ] Yes
- [x] No

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
~8 hours

### Acceptance Criteria

- [x] A durable, shareable artifact about forking open source applications has been created and shared publicly.

**Comment by rahearn** [comment]
WIP: https://docs.google.com/document/d/1EIhM9OaZ53554QPqMTQmEK0ERoKJoCZ9n-bQJexw6EQ/edit#

**Comment by rahearn** [comment]
#mvb posted: https://gsa-tts.slack.com/archives/C4E6XDA8Y/p1684331383760769

**Comment by alexbielen** [comment]
Excellent and a really interesting read. This looks like it meets acceptance criteria and is ready to close. Does that match your understanding, Ryan?

**Comment by rahearn** [comment]
For certain definitions of "publicly". I'd like to take this from #mvb to a truly public blog post, I'm not sure if that fits within this scope, or if it's something I should just track myself as it will cross beyond my time on TLC.

**Comment by alexbielen** [comment]
I think I'm happy with this for now and definitely think you should publicly blog it too! But we have something "durable and shareable" about this approach and I'm happy with that!

**Comment by rahearn** [comment]
Closing issue with #mvb, will track a public blog post through the 18f/blog-drafts repo

**Comment by rahearn** [comment]
Blog post issue: https://github.com/18F/blog-drafts/issues/866
