### ISSUE TITLE
Create plan for piloting resources by project phases doc

### ISSUE THREAD

**Issue by austinhernandez** [18F/TLC-crew#224]
## User story

As a 18F project team member, I need resources and best-practices so that I can better integrate with my workflows and work efficiently

### Additional information about the request

@janelx and @austinhernandez put together links from [Guides IA sandbox](https://docs.google.com/spreadsheets/d/1p-qz4tctoRItMkrINCwo5A5cE4d_98ofkLO2qcO96mY/edit#gid=0), 
[Delivery School draft](https://docs.google.com/document/d/1-yPhvggQLzeGJBmbLRa5MHoXtSCmJTw68Es7ZcIUayI/edit#) , and [18F Project phase documentation](https://docs.google.com/document/d/1GTyor4wV87QXLIutMh__pg0FZTG--NY9XCfvdlFw6fQ/edit#heading=h.gthrqcuqvo5s) to create V1 of the [18F Resources by project phase doc](https://docs.google.com/document/d/1j2v99Ff-WdeU9h5-n2GfNmwuf3oJMtHnaPi3CPecarA/edit#). 

We want to improve this document to ensure it meets the need 18F staff first, before looking into how this resource will work for an external audience.

## Background

Follow on work from #175 where the original hypothesis: "...organizing our resources, methods, and guides around our 18F project phases will help us achieve our strategic bets ([LT update deck for reference](https://docs.google.com/presentation/d/1blkbjomC4v_lx4jjgVT08Qgi4oetMvNzwMpKSgZhisA/edit#slide=id.g1bfeff297f0_0_231)) and will better meet the needs of new 18F staff (rather than external audiences)"

### Open Questions

We tried to align with original documents as much as possible, but some didn't fit into the project phases neatly in the sections. We would like to:

1. Ask questions 
2. Raise potential challenges
3. Understand the experience of 18F staff using project resources
4. Design for the 18F project team audience
5. Improve and iterate

  - This document feels very cumbersome and there are too many pages of text which makes it hard to scan and skim. Is Google Docs the right place to house this information?
     - We clarified that whoever picks this up can move it to sheets or something they feel is better suited / more easily testable
  - There are several instances where an activity can be done in multiple places. Could we consider "tagging" and search instead of scanning.
    -  yes
 - ~Should the sections (eg Accessibility and Hiring) have several links (eg resume review guide, phone screen guide, etc.) or just one link to the section?~
  - Where will it live?
  - When will this roll out to external audiences?
     - The focus is on internal audiences right now. TBD on whether this will ever roll out to external audiences and we're unable to put a timing expectation on that.  

Remaining Qs that would be good to address as part of this work:
  - How will we know if we are successful?

Qs that are outside the scope of this issue and will likely be addressed in #233 
  - Who owns it?
  - How will it be maintained?

  

### Point of contact on this issue
@austinhernandez @janelx (as well as original contacts from #175)
 
### Billable?

- [ ] Yes
- [x] No
If yes, tock code:

### Timeline
 
Does this need to happen in the next two weeks?
- [ ] Yes
- [ ] No
 
## Acceptance Criteria

- [ ] We have a plan for how we'll pilot this doc with 18F teams. 
- [ ] Pilot plan includes:
        - goals/signals/metrics (how we'll know we're successful)
        - Who, how many project teams we'll pilot this with and for how long
        - any relevant considerations for team's inclusion in the pilot
        - pilot launch considerations (necessary preconditions, how we'll invite / onboard teams to the pilot and what they can expect)
        - how we'll collect pilot data 
        - how we'll incorporate learnings from the pilot /

**Comment by austinhernandez** [comment]
@MelissaBraxton @alexbielen — here is the proposed follow on work for #175. 

Just a heads up, Janel is OOO and hasn't had time to give her suggestions yet

**Comment by MelissaBraxton** [comment]
Thank for getting this started, @austinhernandez and @janelx:  

I see that the acceptance criteria is about having a plan for usability testing, which I agree is the next step!  

Additional details re: what I see as the scope of this issue is a research plan that includes 

- research Qs
- hypotheses and assumptions to test
- what we need to do to test these assumptions 
- who we need to recruit and how
- what we need make and/or prototype in order to carry out that research.

**Comment by alexbielen** [comment]
I removed the references to "new 18F team members" since this is intended for all 18F staff that are on project teams.

**Comment by MelissaBraxton** [comment]
@donnykwan and @evoeges - Here's an [example of a pilot plan](https://docs.google.com/document/d/1S30BJ3wEx9hYCyfm1HZdHUgeIXdVN8I6ctTswN6BmP4/edit#), for reference.

**Comment by MelissaBraxton** [comment]
Thanks @evoeges and @donnykwan -  this is looking great! I left some comments and suggested edits. Once you have a sec to resolve those, I think we can call this done. 

I created an epic to cover executing on the plan (#251) and the first follow on issue that will likely come in to next sprint is #245.  

@evoeges If you could hop in and refine #245 prior to increment planning on 6/6 if you can, that would be awesome. Nice work!

**Comment by alexbielen** [comment]
@MelissaBraxton Just a heads up that I believe @evoeges is out on leave next week

**Comment by donnykwan** [comment]
Shall we close this @alexbielen @MelissaBraxton ?

**Comment by MelissaBraxton** [comment]
Yep, @donnykwan - sounds good to me!

**Comment by donnykwan** [comment]
Close.
