### ISSUE TITLE
Fill in gaps in design templates

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#229]
### A description of the work
We have this inventory of [design templates](https://airtable.com/apptZqDMNhC3sEtXZ/tbl7PysIe9LJ93SiQ/viwbEd0Z8K8CwRshS?blocks=hide), but there are gaps! this issue is finding examples and making templates where we have none. 

### Point of contact on this issue
@MelissaBraxton @lauranash18f 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [X] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [x] We have a current, complete inventory of templates and examples for the design deliverables we've previously identified as core to our practice.

**Comment by HannaSChang** [comment]
@MelissaBraxton @lauranash18f - 

Here is a [draft document](https://docs.google.com/document/d/1swc3LMZWRQgxdS6bqT-HY4Vekd4a3K-pSBIrKyLCKkM/edit?usp=sharing) for the design templates that's ready for your review. I tried to fill in the gaps as much as I could, but there are still a couple of examples that are missing for various reasons: 1) some have templates that are straightforward enough where examples may not be too beneficial (such as email templates), 2) they're not easily accessible or contain private/sensitive information, or 3) they've been difficult to locate.

Feel free to reach out to me if you have any questions.

**Comment by lauranash18f** [comment]
Absolutely thrilling, can't wait to dig in! When do you need the review by? (or, if there's no deadline, when would it be convenient for you to have feedback?)

**Comment by HannaSChang** [comment]
Thanks @lauranash18f! Do you have capacity to look at it this week (I'll be OOO all of next week)? If you don't get a chance to review this week then I'm sure we can have someone else on the team take over this issue while I'm out/off the team. :)

**Comment by lauranash18f** [comment]
Yes, I can review this week — thanks for the quick reply!

**Comment by HannaSChang** [comment]
Thank you @lauranash18f for reviewing and cleaning up the template library! As Laura has mentioned, this should be a living database that will need to be worked on and updated on an ongoing basis. Will continue to try to fill in the gaps as needed, but I'll mark this issue as done for now. :)
