### ISSUE TITLE
Get organizational alignment on proposal for how TLC facilitates organizational learning through project refelections

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#235]
### A description of the work
The scope of this issue is to get alignment on [this proposal](https://docs.google.com/document/d/1EVqNl2khVBGQpzgU46SnzJosNfjpkUjZNAX6OvtsHes/edit#) for how TLC crew supports organizational learning via project reflections. 

Folks picking up this issue should familiarize themselves with the "art of alignment" framework and use it to engage relevant stakeholders in refining and aligning on the proposal that everyone can commit to putting into action. 

### Point of contact on this issue
@MelissaBraxton and @alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
About 2 weeks, but the work will likely be intermittent, as there will likely be some schedule dependencies. 

### Acceptance Criteria

- [ ] We have stakeholder consensus on how TLC crew will support organizational learning via project reflections. 
- [ ] Next steps to implement the proposal  are documented as new issues.

**Comment by MelissaBraxton** [comment]
Moving this back to the backlog until we chat with Andrew on 6/9 about the next steps he'd like to see here.

**Comment by MelissaBraxton** [comment]
I made a few minor edits to the proposal based on a Slack thread about this.  @alexbielen  - If this looks good to you, I think you can accept my edits and we can call this done!

**Comment by alexbielen** [comment]
I accepted the edits! LGTM
