### ISSUE TITLE
Augment MVP project resources by phase doc by mapping activities to resources

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#236]
### A description of the work
This work is to further refine the output of #175 by designing a way for 18F staff to see which resources map to specific **activities** in each phase. We talked about adding a column for "activity" and using an approach similar to how you've represented chapter, as an example. 

### Point of contact on this issue
@MelissaBraxton 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?
One day

### Acceptance Criteria

- [ ] The [resources by project phase doc](https://docs.google.com/document/d/1j2v99Ff-WdeU9h5-n2GfNmwuf3oJMtHnaPi3CPecarA/edit#) includes a way to see which resources map to specific activities in each phase.

**Comment by janelx** [comment]
hi @MelissaBraxton I attempted this but had difficulty categorizing activities that made sense. Instead I added a proposed outline depending on the user stories/needs. [You can find it at the end of the document it here] (https://docs.google.com/document/d/1j2v99Ff-WdeU9h5-n2GfNmwuf3oJMtHnaPi3CPecarA/edit#heading=h.e86i6c1202fi). Could also wait to do anymore design till there a clearer strategy or audience is defined.
