### ISSUE TITLE
Research potential resources to fill known gaps in 18F doctrine

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#247]
### A description of the work
The scope of this work is to research whether 18F has existing documentation to fill gaps in our [MVP 18F doctrine inventory](https://docs.google.com/document/d/1j2v99Ff-WdeU9h5-n2GfNmwuf3oJMtHnaPi3CPecarA/edit#). Gaps we're currently aware of:  

Project phases and activities that we have already highlighted as having no resources:
 - Phase: **Transition to partner** / activity: **document existing practices**
 - Phase: **Discovery** / **activity:** Draft proposal and SOW for next phase of 18F; **activity:** Desk research
 - Phase: **Kickoff** / **activity:** Tock line created
 - Phase: **Project closeout** / **activity:** Partner Satisfaction Survey; **activity:** Share agency and domain context within 18F

### Point of contact on this issue
@MelissaBraxton 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] For the gaps in our MVP 18F doctrine inventory, we've either validated that no resources exist / added resources that we've found to fill in gaps

**Comment by MelissaBraxton** [comment]
@austinhernandez  - I've started a minor re-org [here: ](https://docs.google.com/document/d/1DGNs2cTkckuEjrI2fxYU9-5Nk-ALLOkbecYWo85czwE/edit#heading=h.qk3xeuuidusn) - I don't think it impacts your work too much, but could be a place to add your notes.

**Comment by austinhernandez** [comment]
followed up with melissa 6/8 and tracked down some resources. OOO friday-monday and will pick up then!

**Comment by austinhernandez** [comment]
[Updated 18F Doctrine for 18F teams](https://docs.google.com/document/d/1DGNs2cTkckuEjrI2fxYU9-5Nk-ALLOkbecYWo85czwE/)

Summary of work below, some open comments in the doc. Considering this done @MelissaBraxton 

**Filled in and added resources for:**
- Tock line created✅
- Draft proposal and SOW for next phase of 18F✅
- Partner Satisfaction Survey ✅ (and included GSA customer satisfaction links)

**Also added**
- templates and agendas for different kickoff
- more context to design methods
- Link to define [first slice(s)](https://drive.google.com/file/d/1JVEqbQTCM0vjadlAg0P_jt6ZkjSZd-yE/view?usp=drive_link) of software development
- link to [TTS Handbook: Launching software](https://handbook.tts.gsa.gov/#launching-software)


**Outstanding**
- Cant find any resources on "desk research." Double-checked in the Design chapter slack channel
- "Document existing practices" seemed pretty open ended and I identified one resource but there may be more? 
- "Share agency and domain context within 18F" was confusing to me / not sure what is specifically needed here
- Tell the story seems vague and theres a lot of ways to do this. Not sure what is specifically included here so I added a couple of resources. 


**Questions:** 
- Not sure of the best way to format subsections within guides. When is it relevant to show a subsection vs the entire guide? 
- Note to think about how high-level or granular we are adding resources. Is it just the "UX Research Guide" or is it the "Make research actionable" section on the UX Research Guide" OR is it the "Sharing research" subsection of the "Make research actionable "section?
- Sections in the Product guide under "Define the future state." Its also missing the subsection "Define the problem"
- Found several resources for "Draft proposal and SOW for next phase of 18F" but feel like theres more of a tie in with this and "Share agency and domain context within 18F" in the Project closeout phase.

**Comment by MelissaBraxton** [comment]
Thank you @austinhernandez  - This all makes clear sense. Moving to done! 🎉
