### ISSUE TITLE
Offboard Erin Gamble

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#250]
# For team leads 
- [x] Remove the person offboarding from 18F-TLC google group, which will uninvite them from meetings
- [ ] At the person offboarding's last sync with the team, insitgate a round of applause to thank them for their contributions!

# For person offboarding
- [x] Close tickets and ensure acceptance criteria have been met.
- [x] Ask someone to peer-review before closing or committing
- [ ] Document in-process tickets.
  - [x] In the comments section, provide any documentation detail, next steps, or suggestions. [Example.](https://github.com/orgs/18F/projects/41?pane=issue&itemId=20701671) 
  - [x] Tag @melissabraxton and @alexbielen in the comments of the issue if they should be aware of it’s status
  - [ ] Do not change the status of the ticket or put it back in the backlog, leave them as is.
- [ ] Create new tickets that could be considered for follow-on work. 
- [x] Note them in the comments of the original ticket. [Example.](https://github.com/18F/delivery-assurance/issues/33)
- [x]  Remove yourself from the [TLC Crew Github Group](https://github.com/orgs/18F/teams/18f-tlc-crew/members) 
- [x]  Remove yourself from #18f-tlc-crew, or stick around and follow along--it’s up to you!
- [x]  Fill out the [exit survey](https://docs.google.com/forms/d/e/1FAIpQLSeREJJ0ceZxS_AOyAiMgKRQiZRgdTondFuJ1ReCYl5wEBmJQg/viewform?usp=sf_link)

**Comment by egamble23** [comment]
@MelissaBraxton , just a friendly note that the exit survey has the former Delivery Assurance name. Not a big deal but just wanted to flag in case it's helpful re: the name change! :)

**Comment by egamble23** [comment]
For the checklist, I've checked items that apply. No remaining tickets that are open associated with me. So I think I can move this to "done." :) I'll do so. 

Fyi, the sync meetings have been removed from my calendar. Maybe I can do a post in the Slack channel to thank folks for collaborating with me as a new colleague. Thanks!
