### ISSUE TITLE
Design/Technical Spike:  Surface risks in updating USWDS from 2.x to 3.x in Guides consolidation

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#253]
### A description of the work
The scope of this issue is to review the de-risking guide and identify potential risks and recommendations on how to ensure that the site is set up to responsively use current USWDS components. This work is intended to be concurrent with the work to migrate the site to the new SSG in #246 

### Point of contact on this issue
@MelissaBraxton, @kfoley-18F, @alexbielen   

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [X] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

**How much time do you anticipate this work taking?**
1-2 days of effort

### Acceptance Criteria

- [ ] We've communicated what it needed to ensure that the de-risking guide will responsively use the newest USWDS components to the developers working on the migration to 11ty.

**Comment by MelissaBraxton** [comment]
What we expect, based on discussion in increment planning (6/6):
 - Fork the derisking guide, update USWDS to 3 
 - then a visual pass / QA check
 -  document what broke / what looks odd / where we might run into issues as we do more of this with more of our sites

**Comment by austinhernandez** [comment]
updating with my pre-vacation status. waiting for a front-end developer (probably @jasnakai) to apply USWDS 3. then, i will review it and mark any issues!

**Comment by jasnakai** [comment]
Updated the USWDS install from 2.12 to 3.0. Some things broke but I am fixing the issues by following the documentation.

**Comment by MelissaBraxton** [comment]
@jasnakai and @igorkorenfeld  - With where we're at in the migration and how we're considering styling as we do so, I'm thinking we might be able to call this issue done?

**Comment by jasnakai** [comment]
@MelissaBraxton I would say "yes". We discussed it briefly when we last met with Sarah. Thanks!
