### ISSUE TITLE
Create GitHub epic and issues for Guides technical consolidation

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#259]
### Context
18F recently chose Eleventy as its [default static site generator (SSG)](https://docs.google.com/document/d/16DMVEq0-O3mgz6rxJCGYu3sdDSwePGBmLA94wyAf_ho/edit#heading=h.dbuhuf33m8ub). The TLC Crew has been working on a [technical plan ](https://docs.google.com/document/d/16DMVEq0-O3mgz6rxJCGYu3sdDSwePGBmLA94wyAf_ho/edit#heading=h.dbuhuf33m8ub) to re-platform the disparate guides into a single repository, built with Eleventy, with redirects from the old guides to the new. 

### A description of the work
We need to turn the technical plan into increment-sized (or smaller) issues for the TLC Crew board. 

### Point of contact on this issue
@alexbielen 

**Billable?**

- [x] No

**Skills needed**

- [x] Engineering

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes

How much time do you anticipate this work taking?
~10

### Acceptance Criteria

- [ ] There is an epic that captures the guides replatforming work in one ticket
- [ ] There is an issue for each guide with clear steps on how to implement the replatforming

**Comment by julialeague** [comment]
Along with other issues, I noted in our technical plan that a separate task should be opened to define and document both the PR and contributions process for the new guides repo. I want to note that here so that it doesn't get lost in the shuffle!
