### ISSUE TITLE
Add in Content content to new replatformed Guides and Methods

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/TLC-crew#289]
Part of the Guides Replatforming Epic #269

### A description of the work

For the Guides and Methods replatforming work (see [Tech Spec](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#), we need to add in the Content Guide into the site, including content (Markdown files) and assets (images, CSS files, JS files, any additional files).

### Point of contact on this issue
@alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
Less than a week

### Acceptance Criteria

- [ ] (leaving as draft until we determine if the steps in #284 are correct)

**Comment by michelle-rago** [comment]
Review checklist developed by @geekygirlsarah.

[ ] Make sure there's some icon on the home page that links to the guide
[ ] visit every page in the main navigation and sidebar navigation to make sure they load
[ ] Click at least a couple of links within the guide pages to make sure they navigate to the correct guide page
[ ] The title on every page should be the 18F logo and the name of the guide
[ ] Check that all images on the production guides match the same images on the new guides
[ ] Look for any stray { ... } or {{ ... }} type curly brace tags. They shouldn't be visible on these pages.
[ ] Make sure the appropriate navigation shows up on every page (and not a test menu)
[ ] Make sure the navigation menus on new and old guides have all the same links
[ ] Internal/private links (like Google Docs) should have a lock icon and Slack channel links should have a Slack icon
[ ] Page aesthetics should be about the same across all pages. (like one page isn't wider than others, different font sizes, etc.)
[ ] The main USWDS-type theme should be on each page. (18F icon, search bar, "An official website of the US gov", GSA footer, etc.)

**Comment by MelissaBraxton** [comment]
@michelle-rago  - I recall that you were going to pick up this review. Is that right? If not I just want to make sure we have a reviewer identified.

**Comment by michelle-rago** [comment]
Yes @MelissaBraxton, this is done https://github.com/18F/approaches/pull/23.
