### ISSUE TITLE
Add in UX content to new replatformed Guides and Methods

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/TLC-crew#291]
Part of the Guides Replatforming Epic #269

### A description of the work

For the Guides and Methods replatforming work (see [Tech Spec](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#), we need to add in the UX Guide into the site, including content (Markdown files) and assets (images, CSS files, JS files, any additional files).

### Point of contact on this issue
@alexbielen 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
Less than a week

### Acceptance Criteria

- [ ] (leaving as draft until we determine if the steps in #284 are correct)

**Comment by AnitaYCheng** [comment]
Planning to split this into 2 tickets, because there are a lot of pages to move.

**Comment by MelissaBraxton** [comment]
I'm going to archive this, since the work os covered under two other issues.
