### ISSUE TITLE
Create a home page on new replatformed Guides and Methods

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/TLC-crew#294]
Part of the Guides Replatforming Epic #269

### A description of the work

The scope of this issue is to mock up an MVP homepage for the re-platformed methods and guides. We understand that there is concurrent work to refine 18F site templates and branding, but we need a central place from which users can navigate to the guides in the near term. 

### Point of contact on this issue
@MelissaBraxton 
@adunkman (18f guides product owner)

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [X] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] We have a peer reviewed Figma mockup of a homepage for the re-platformed guides that provides users a central place from which to navigate to individual guides
- [ ] We've documented steps needed to implement the mockup as a new issue

**Comment by MelissaBraxton** [comment]
Hey there, @igorkorenfeld  - Is this issue redundant now, since I think we already have it in #371?
