### ISSUE TITLE
Add Pa11y to CI/CD process of replatformed Guides and Methods

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/TLC-crew#297]
Part of the Guides Replatforming Epic #269

### A description of the work

Add Pa11y automated accessibility scanning to our CI/CD process.

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [x] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] Pa11y can be run locally
- [ ] Pa11y runs on every PR

**Comment by igorkorenfeld** [comment]
PR: https://github.com/18F/approaches/pull/25
