### ISSUE TITLE
Content strategy to establish naming conventions and URL structure

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/TLC-crew#299]
Part of the Guides Replatforming Epic #269. This work includes researching creating new baseurl variable for replatformed Guides and Methods and what the url structure should be. 

### A description of the work

(draft placeholder)

### Point of contact on this issue
Who can we follow-up with if we have questions?

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] We've documented recommendations on what the naming conventions and structure for the replatformed guides URL(s) should be.

**Comment by geekygirlsarah** [comment]
https://docs.google.com/document/d/1gqSYX8lYqAOkX2jlbWaLOPi3tifbvZU_xbFSZM1S5Js/edit    <-- original notes
https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#   <-- tech spec (a more solidified, directed document of decisions)
https://docs.google.com/document/d/1JOVozKiiB5iP73QdFYprCitx6-y7L_vf5PMXXObedOU/edit   <-- conversion to tickets/issues (us thinking through how the tech spec turned into Github tickets)

@michelle-rago  Probably the middle is most useful, maybe the first one if you want to see all the things we thought through. but URL ideas and conventions and redirects and all those things are in there.

**Comment by michelle-rago** [comment]
[Spreadsheet with existing and proposed URLs](https://docs.google.com/spreadsheets/d/12AQs_R5Hi7NgWovmqwJvGxwrBCnpjpVsBV4A4HrE2tI/edit#gid=0)

**Comment by MelissaBraxton** [comment]
@geekygirlsarah  - I believe you've reviewed this.  Anything else needed here before we move this one to done?
