### ISSUE TITLE
Illustration for blogpost: Catch up with TANF Data Portal

### ISSUE THREAD

**Issue by cmajel** [18F/TLC-crew#312]
## User story
As someone scanning the 18F blog or social media, I want to see images that reflect the post's content and nudge me to read it.

As a contributor to the 18F blog, I want my blog art to match 18F style and scale across multiple formats.

### Additional information about the request
* [18F blog art guidence](https://github.com/18F/blog-drafts#imagery)

## Background

We're doing a "catching up with the TANF Data Portal Project" post, and I'd like a banner image to go with it.

Here are some concept ideas in order of preference (I can also share the post draft once someone is assigned for more context)
* The long game; tech and modernization as a marathon, not a sprint
* Opening up communication channels
* Data transmittal

And, the abstract art style I'd like to emulate (from past posts):
* [A federal guide to de-risk government technology projects](https://18f.gsa.gov/2020/09/09/a-federal-guide-to-de-risk-government-technology-projects/)
* [Six years improving the experience of government](https://18f.gsa.gov/2020/03/19/sixth-anniversary/)
* [READMEs for you and me](https://18f.gsa.gov/2020/03/05/readmes-for-you-and-me/)
* [Even with a design system, you still need a designer](https://18f.gsa.gov/2020/02/06/even-with-a-design-system-you-still-need-a-designer/)

### Point of contact on this issue

You can contact me @cmajel 
 
### Billable?

- [ ] Yes
- [x] No
If yes, tock code:

### Timeline
 
Does this need to happen in the next two weeks?
- [ ] Yes
- [x] No

Not next two weeks but would prefer July to align with approvals
 
### How much time do you anticipate this work taking?

Less than 2 weeks

## Acceptance Criteria

- [ ] Blog art concepts are created in line with [18F blog art guidance](https://github.com/18F/blog-drafts#imagery)

**Comment by melchoyce** [comment]
Hey @cmajel, is there an outline or a draft of the post I can review as well?

**Comment by cmajel** [comment]
@melchoyce yes! [Here's the draft.](https://docs.google.com/document/d/108pkJzhAAzDNl1D7pBbnDu4pMpSVsI6qBAIM9AHLLm0/edit#)

**Comment by melchoyce** [comment]
@cmajel Here's a couple ideas around data sharing and communication!

![Communication 1](https://github.com/18F/TLC-crew/assets/2846578/9e3e5b8c-5c78-467b-bd01-b5285c5fb0f9)
![Communication 2](https://github.com/18F/TLC-crew/assets/2846578/84c3bebe-2fda-4312-82aa-47a6dceebcc5)
![Communication 3](https://github.com/18F/TLC-crew/assets/2846578/2283f725-5275-435a-88f0-7a15e3a67e35)
![Communication 4](https://github.com/18F/TLC-crew/assets/2846578/be02c3b1-96e2-45e5-9590-4a982fe0b6c0)

**Comment by cmajel** [comment]
@melchoyce thanks for these! Per our chat, I'd be interested in seeing some more abstract concepts and exploring the "it's a long game" concept more.

Here's some sketchy ideas to give a sense of what I'm thinking (not committed to any of these, but leaning more abstract)

something building over time
![growing-web](https://github.com/18F/TLC-crew/assets/2374206/580bb80c-097e-40d4-90fe-b8e69cea806b)

growth/takes time to bear fruit or flowers or substance 
![plant](https://github.com/18F/TLC-crew/assets/2374206/ceaa2751-f3d8-41d4-904d-360fcefe38ce)

long road with upward focus
![road-up](https://github.com/18F/TLC-crew/assets/2374206/c0b4c50f-9605-45ac-b254-1f1ddd015e20)

conceptual data transfer (overlaps, exchange and continue)

![dt-1](https://github.com/18F/TLC-crew/assets/2374206/3147a9c1-beaa-4524-92c2-b7e4125c84f5)
![dt-2](https://github.com/18F/TLC-crew/assets/2374206/14dfa647-2479-4c8e-b366-d8bdbc7e982f)

**Comment by melchoyce** [comment]
Didn't have a chance to finish this up before spending the rest of the sprint afk. I'll be circling back to it this week!

**Comment by melchoyce** [comment]
I really like the plant metaphor! Here are two ideas around that:

![image](https://github.com/18F/TLC-crew/assets/2846578/33a2a79c-3cba-440b-8449-203d888f57fe)
![image](https://github.com/18F/TLC-crew/assets/2846578/ad24fee6-2cb4-466c-b3d3-5da168f24cff)

**Comment by melchoyce** [comment]
I'm offboarding from TLC now, but these designs can be found on Figma:

https://www.figma.com/file/bSoIq1Gk9iWUks83uv1zVu/Catching-up-with-the-TANF-Data-Portal-project?type=design&node-id=0%3A1&mode=design&t=bqeTV1zfU4NKPxPT-1

**Comment by MelissaBraxton** [comment]
@cmajel  - Since you're the PO on this, would you say the acceptance criteria are met?

**Comment by cmajel** [comment]
Catching up after OOO and yes! This is good to close.
