### ISSUE TITLE
Write content to fill in gaps in our doctrine re: qualitative data analysis

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#315]
### A description of the work
This issues covers following through on the recommendations laid out **here** re: how and where we should document our recommended approach to coding and analyzing qualitative data. [I've detailed the challenge a bit more in this doc.](https://docs.google.com/document/d/1rJtx1-KDmYirvTMecaKeVqoD79dDoL8j9vKdMttIzdU/edit#heading=h.1htjitaygokv
)

### Point of contact on this issue
Who can we follow-up with if we have questions?
@MelissaBraxton 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [X] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
About a week

### Acceptance Criteria

- [ ] Documentation on our recommended approach to qualitative data analysis is understandable and findable to 18F teams

**Comment by MelissaBraxton** [comment]
@boonerang  - Can you add the link to your doc recommending how/where we implement this content to the "description of the work" above?

**Comment by boonerang** [comment]
[Doc explaining the details as Melissa noted above](https://docs.google.com/document/d/1rJtx1-KDmYirvTMecaKeVqoD79dDoL8j9vKdMttIzdU/edit#heading=h.1htjitaygokv
)

**Comment by boonerang** [comment]
Doc linked here: [Writing up data analysis.](https://docs.google.com/document/d/1rJtx1-KDmYirvTMecaKeVqoD79dDoL8j9vKdMttIzdU/edit#heading=h.t5m8ewqd2nfy)
