### ISSUE TITLE
Get alignment w/Ron and Jessica on plan to research refinements to the 18F brand

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#318]
### A description of the work
The intent here is that this is the first step before as part of the #314 epic.  We have a draft research plan on how we propose to research refinements to the 18F brand, but we want to make sure that the key stakeholders are aligned on this plan before we move forward. Key stakeholders are Andrew Dunkman, Liz Camerlin, and Ron Bronson. 

### Point of contact on this issue
@MelissaBraxton and @quarterback 

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [X] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] Key stakeholders have consensus on our plan for carrying out 18F branding research.

**Comment by MelissaBraxton** [comment]
@jdamis4XD  - I think this is in progress, but I think it could also move to "blocked/waiting" since Andrew has been out all week?

**Comment by jdamis4XD** [comment]
@MelissaBraxton 
I believe @austinhernandez spoke to @quarterback before going on vacation about the scope of work and got the green light that we could proceed. @quarterback Can you confirm if we need any other outstanding sign-off?

**Comment by quarterback** [comment]
@jdamis4XD @MelissaBraxton Melissa is right, I have some newer info since we met, let's sync next week. I don't want us to get too far down on this before we get BD/Delivery looped in more, it's kind of the 1B to #324, which has to be the priority, but can happen in parallel, but needs to be more in concert with BD's goals so that we're not just off on an island doing this part. Let's sync next week about it!

**Comment by jdamis4XD** [comment]
@quarterback @MelissaBraxton Ok, I will put something on the calendar and move this ticket to blocked.
