### ISSUE TITLE
Preliminary desk research on current 18F site

### ISSUE THREAD

**Issue by austinhernandez** [18F/TLC-crew#321]
### Additional information about the request

Part of #313 

## Background

Changes to the 18F site are being made, but how will we know we are successful? Desk research should give 18F designers more information about how the site is currently working, who is using it, and how are partners are currently working with us.

### Billable?

- [ ] Yes
- [X] No
If yes, tock code:

### Timeline
 
Does this need to happen in the next two weeks?
- [X] Yes
- [ ] No
 
### How much time do you anticipate this work taking?

1-2 days

## Acceptance Criteria

- [x] Search for internal documents about 18F site and our users including analytics, surveys, biz dev resources, etc.
- [x] Review 18F analytics data
- [x] Pull competitor analysis
- [x] Review parter satisfaction survey

**Comment by jdamis4XD** [comment]
@austinhernandez Here is the [GA stats ](https://docs.google.com/spreadsheets/d/1pYD7_q3G6ElRWy5ucyBB-brVrXxcaSiDpTqNSTrhqk0/edit?usp=sharing) I pulled and analyzed. We can discuss when you get back if we want to analyze anything else.

**Comment by jdamis4XD** [comment]
I completed the competitive analysis last week and limited the analysis to just [Public competitors ](https://docs.google.com/spreadsheets/d/1bU3mm2UP5jOmVWxdwwbm7NhympywBfMi8kqoYwShXN4/edit#gid=814299701) after confirming with @austinhernandez that 18F doesn't consider for profit consultancies as competitors.  I don't think prospective agency partners have that viewpoint, so I might still investigate.

**Comment by jdamis4XD** [comment]
Reviewed the Partner survey and shared the file with @austinhernandez to review when he gets back in the office.
