### ISSUE TITLE
Update TLC crew initiative brief and roadmap

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#323]
### A description of the work
The scope of this issue is to review and update our initiative brief and ensure that it accurately conveys recent progress and developments.

### Point of contact on this issue
@MelissaBraxton 

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

**How much time do you anticipate this work taking?**
About a day

### Acceptance Criteria

- [ ] Our initiative brief is current and accurately communicates problems we're addressing and why, how we're helping, what success looks like, and where we're at a high level that readers can understand with little effort.

**Comment by MelissaBraxton** [comment]
@alexbielen  - I made some updates. Can you review and make sure I captured everything? If it all looks good, we can move this to done!

**Comment by alexbielen** [comment]
Review and it looks great! Closing this.
