### ISSUE TITLE
Create research instrument for gathering doctrine feedback

### ISSUE THREAD

**Issue by boonerang** [18F/TLC-crew#328]
### A description of the work
The scope of this issue is to build on the work of #245  and now create the stimuli for the lightning research needed to get the MVP 18F doctrine for 18F team's artifact ready to pilot, as is laid out in the pilot plan, #224.
  
We will start with Google Forms as the easiest way to create a quick survey that all 18F members can access.

### Point of contact on this issue
@MelissaBraxton  @boonerang 

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [X] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [X] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?
About a week

### Acceptance Criteria
- [ ] We will have an operational survey form we can share to gather feedback
- [ ] We have tested the form with multiple users to compare inputs and outputs.

### Tasks
 - Draft survey in Google Forms
 - Create doctrine artifact (doc or sheet for LT) to review and react to
 - Test survey and refine questions
 - Tag @alexbielen and @MelissaBraxton to review

**Comment by MelissaBraxton** [comment]
I added a task to create the doc or sheet that LT will review

**Comment by boonerang** [comment]
Working on survey _and_ source doc (what LT will actually review).

**Comment by boonerang** [comment]
Instrument switched to an [inventory spreadsheet with assisting content](https://docs.google.com/spreadsheets/d/19AVzPbrrlaCYNyR2IYYQaZ_EHuqzBQrF2B5SPgMzph8/edit?usp=sharing). Meetings this week to refine and plan presenting it to LR.

**Comment by MelissaBraxton** [comment]
All righty, @boonerang! I added a few Qs for you in this [draft explainer doc](https://docs.google.com/document/d/1z5zyhrKRA6mB6q9Ksr8i-2vIvca_9mmsLkpaTuhdcd4/edit). If you could take a look. And I suggested on last tweak to the sheet. 

Once your feeling good about these two things, I think we can share with Selena to view ahead of our Thursday meeting!

**Comment by boonerang** [comment]
Explainer doc updated, doc reviewed with Selena, edits and tweaks made. Marking this as done per Melissa's comments yesterday.
