### ISSUE TITLE
Create and launch doctrine survey

### ISSUE THREAD

**Issue by boonerang** [18F/TLC-crew#329]
### A description of the work
The scope of this issue is to build on the work of #245 and #328 to launch the survey for feedback as laid out in the pilot plan. #224.  The form will have been created and now the survey content will be decided and launched,

### Point of contact on this issue
@MelissaBraxton @alexbielen @boonerang 

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [X] Any human
- [X] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [X] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
About a week to craft the survey, feedback may take a while.
Launching the survey will be one task, depending on the approach we may send multiple surveys based on topics. If multiple surveys are sent they will likely be spread across weeks.

### Acceptance Criteria
- [ ] We have a draft of the survey and feedback from team on the content
- [ ] The form is launched

### Tasks
 - Draft survey in Google Forms
 - Test survey and refine questions
 - Tag @alexbielen and @MelissaBraxton to review

**Comment by boonerang** [comment]
Clarifying we are using a spreadsheet now, not a survey. The [spreadsheet is here](https://docs.google.com/spreadsheets/d/19AVzPbrrlaCYNyR2IYYQaZ_EHuqzBQrF2B5SPgMzph8/edit#gid=1681405890) and will likely have a tweak or two when folks first use it.

**Comment by SelenaJV** [comment]
Cool. I like the changes @boonerang. Felts much more usable. Looking forward to hearing @adunkman's thoughts.

**Comment by MelissaBraxton** [comment]
@boonerang   - This should be in "blocked/waiting" until @alexbielen and I meet with @adunkman on Monday 8/21. Our plan is to review the draft with him get his input and any edits before refining and finalizing.

**Comment by MelissaBraxton** [comment]
@boonerang  - W/ today's LT presentation, I think we can consider this launched!  🚀 

Closing.
