### ISSUE TITLE
Step 2: Identify or develop a project plan template using project phases

### ISSUE THREAD

**Issue by christophermather** [18F/TLC-crew#331]
### A description of the work
Building off of [Issue 240](https://github.com/18F/TLC-crew/issues/240), we need to now solicit feedback from the Chief of Delivery on the prototype that we developed. 

Pending feedback, we need to do one or all of the following:

- Incorporate feedback and revise template
- Demo template to project leads and account managers to solicit feedback and determine viability
- Do other ancillary research to locate this prototype among other 18F project management efforts

Recommend creating new tickets once it's clear which of the above we are planning to pursue.

Prototype is [available here](https://docs.google.com/spreadsheets/d/1tkHcojNJtdaGqMtbLL4hwBwHHlXPThuTANFf-gt-ukM/edit#gid=34199553).

Folks that need to 

### Point of contact on this issue
--

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [x] No

If yes, tock code:

**Skills needed**
- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other
- [ ] Timeline

**Does this need to happen in the next two weeks?**

- [ ] Yes
- [ ] No

**How much time do you anticipate this work taking?**
TBD?

**Acceptance Criteria**

- [ ] Prototype is approved by Chief of Delivery

**Comment by MelissaBraxton** [comment]
First step here will be to revise the issue and possibly adjust the scope and sizing following mtg scheduled with Andrew on 7/18.

**Comment by donnykwan** [comment]
@adunkman reviewed and provided good  feedback to the prototype (check list), and suggest we work on the AllTogether (summary ) tab checklist.  This [doc](https://docs.google.com/document/d/1sRUqjvmTPGtB9gGPwzPhRfczhfXgtohY2oH7lVy8xtc/edit) shall provide some real time checklist tasks that can be incorporated into the AllTogether tab.

**Comment by MelissaBraxton** [comment]
Moving to blocked/waiting dependent upon @alexbielen and @MelissaBraxton scheduling time to for Chris and Donny demo the current version with @adunkman and discuss recommended next steps.

**Comment by MelissaBraxton** [comment]
Update: This will move to done following demo on Monday, 7/31. Next step is to create a plan to pilot this covered in #364

**Comment by MelissaBraxton** [comment]
@christophermather and @donnykwan Moving this to done!
