### ISSUE TITLE
Remove new line from all engineering pages

### ISSUE THREAD

**Issue by kewlguy781** [18F/TLC-crew#336]
### A description of the work
There are some engineering pages that have line breaks that caused the word wrap to act weird. This task is to clean up engineering pages so they render correctly. More background: https://gsa-tts.slack.com/archives/C04MSAWM2GM/p1689022005011329

For example, one under on-call page:
![Screenshot 2023-07-17 at 12 37 36 PM](https://github.com/18F/TLC-crew/assets/17609373/cd931267-c763-46df-9228-ff09e35dbfd8)

### Point of contact on this issue
Who can we follow-up with if we have questions?
@kewlguy781 

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [x] Design
- [ ] Content
- [x] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
2-5 Days (require verification and comparison with production's site at https://engineering.18f.gov/)

### Acceptance Criteria

What does "done" look like?

- [ ] A person will need to go through all pages and fix, removing the new line, and make sure the word wrap doesn't cause it to look weird

**Comment by beechnut** [comment]
Extraneous newlines may be a recurring issue, so a systematic fix would be welcome.

First, is there a way to change Markdown rendering settings somewhere in Eleventy so that it ignores these newlines, and behaves more like the Jekyll guides?
Second, if not, would there be a quick and easy way to implement a Markdown linter that auto-fixes line breaks like this?

**Comment by kewlguy781** [comment]
https://github.com/18F/approaches/pull/22/files/f854bb806d78c603e1097cbc90f4299362a383bd#r1265892008

**Comment by kewlguy781** [comment]
I found a way to fix this. If you go to `.eleventy.js` and go to line 103, `breaks: true,`, changing to false, and everything look correct on the engineering side. However because its a system wide change, we need to check in with team. Any thoughts?
@igorkorenfeld @beechnut

**Comment by igorkorenfeld** [comment]
This seems to work, I checked a couple of guides and didn't see anything too odd. Could you also spot check a few guides locally and compare them against the existing ones?

**Comment by kewlguy781** [comment]
Done and is now in main branch. https://github.com/18F/approaches/pull/41
