### ISSUE TITLE
Rewrite 18F case studies to align with a new structure

### ISSUE THREAD

**Issue by michelle-rago** [18F/TLC-crew#342]
- [ ] Rewrite existing [18F case studies](https://18f.gsa.gov/what-we-deliver/) to align with a [new structure](https://docs.google.com/document/d/1CA-um7FWudmwLSRNcag3tCV7LKdqDUH_PXgxM-kmQD0/edit).
- [ ] Develop and publicize template for use on projects

**Comment by michelle-rago** [comment]
> @michelle-rago Is there any prioritization of case studies to be revised in the new structure? Or should I just review them all and pick one I want to start with?

I don't think so. You can poke through and just pick one.

**Comment by michelle-rago** [comment]
Strike my comment! Just chatted with @durland18F. You can look at all the case studies here https://github.com/18F/18f.gsa.gov/tree/main/_services_projects. It would be good to pick more recent examples for starters, like https://18f.gsa.gov/what-we-deliver/doj-crt/. I know it's hard to tell which ones are recent so starting with DOJ CRT is a safe bet.

**Comment by MelissaBraxton** [comment]
I believe this is done with the completion of #346.
