### ISSUE TITLE
Write new issues to break down work of re-platforming the de-risking guide into increment-sized chunks 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#345]
### A description of the work
The scope of this issue is to write new issues to break up #292 so that we can complete the work in 2-week increments. 

### Point of contact on this issue
@MelissaBraxton and @igorkorenfeld 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [x] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] We have well scoped and refined issues to cover migrating the derisking guide in 2 week increments.

**Comment by igorkorenfeld** [comment]
@MelissaBraxton and @alexbielen Just FYI I have split this ticket up. Part 1 is still in #292, and added new issue #353 .

**Comment by igorkorenfeld** [comment]
After starting on #292, I realized that the work could be subdivided into smaller pieces still. 

Updated #292, #353, added #359 and #360

**Comment by MelissaBraxton** [comment]
Thanks @igorkorenfeld! I think we can call this one done. :)
