### ISSUE TITLE
Rewrite a case study using new case study structure

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#346]
### A description of the work
The scope of this work is to rewrite a case study on the 18F website to align with a [new structure](https://docs.google.com/document/d/1CA-um7FWudmwLSRNcag3tCV7LKdqDUH_PXgxM-kmQD0/edit). This issue covers rewriting just one case study to see how well the new structure works and recommend any needed refinements to the structure. 

I recommend that whoever picks this up should start with this one: 
https://18f.gsa.gov/what-we-deliver/tax-court/ 

We can draft the revised content in a Google doc with the understanding that we'll want to draft all of the new case study content in a doc so that they consistently use the new structure before we push any of the revised case studies to the live site. 

### Point of contact on this issue
Who can we follow-up with if we have questions?
@MelissaBraxton and @amandacostello   

**Billable?**
- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?
- [ ] Yes
- [X] No

**How much time do you anticipate this work taking?**
About a week

### Acceptance Criteria

- [x] We have a new draft of a case study that uses the revised case study structure
- [x] Draft has been peer reviewed and revised based on peer feedback
- [x] We've documented any recommended refinements to the new structure and shared them with @durland18F and @amandacostello

**Comment by MelissaBraxton** [comment]
Hey there, @ameliaswong  - @amandacostello, who helped devise the new case study structure is currently working on applying it to one of the other case studies. We're thinking that once either of you has a draft rewrite, that you two can get together and peer review/edit each others work.

**Comment by ameliaswong** [comment]
@amandacostello I can pick up /tax-court/ as Melissa advised above if you're not working on it already. Let me know if I can go ahead or you'd like me to start on a different one.

**Comment by ameliaswong** [comment]
Hi @amandacostello, I've got a [draft of the Tax Court case study](https://docs.google.com/document/d/1orBJdTHIfcoTU6nC5MJvBcp1GiZEPJa6S1u2IVztHi8/edit) ready for review. I based it on the Copy direction voice/tone and pulled from the related blog posts to try and plug some perceived holes. I  followed the new structure as designed, though combined approaches and outcomes, explaining why in the doc. Hopefully I didn't go to far astray. Look forward to your thoughts.

**Comment by MelissaBraxton** [comment]
Amazing! This issue is done, and we'll make new issues to cover pushing the rewritten content live.
