### ISSUE TITLE
Set Guides page title strategy

### ISSUE THREAD

**Issue by beechnut** [18F/TLC-crew#376]
### Problem statement

In the De-risking guide (and probably others), the page title in the tab or `<head>` tag, and the title on the page, are different. We need to decide whether and how to support this, and also what to append to every page title.

For example, [the QASP page of the de-risking guide](https://derisking-guide.18f.gov/qasp/) has a page title (e.g. H1) of "Sample Quality Assessment Surveillance Plan (QASP)" but the page tab title is "QASP | De-risking government technology | 18F". And in the replatformed guides, the site title is appended, so we'd get something like "Sample Quality Assessment Surveillance Plan (QASP) | 18F Approaches", which doesn't seem right either.

### A description of the work

Develop guidance for / a plan for handling page titles, and implement it in the page layouts / front matter.

My hunch is that layouts should, by default, create a tab title that looks like: `page title | guide title | 18F`.

The De-risking guide asserts that page and tab titles should be able to be different, for example, the tab title of one page uses an acronym, which is more navigable and possibly better for searching in browser histories. Personally, I'm not so sure, and would lean towards the simplicity of not supporting custom tab titles.

### Point of contact on this issue

Created the issue: @beechnut 
Validated the problem: @igorkorenfeld 
Otherwise: @alexbielen @MelissaBraxton 

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

Any of:

- [ ] Any human
- [x] Design
- [x] Content
- [x] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [x] A decision has been made on whether to support custom page titles.
- [x] The decision is fully implemented in 11ty layouts / front matter.

**Comment by AnitaYCheng** [comment]
Gathered my findings and notes from a discussion with the TTS content guild in [this GSlide](https://docs.google.com/presentation/d/1Cf7ne7Ypnw_VR6-3NcDhUxNte5sSee5o7f1oiCw5Xeg/edit?usp=sharing).

I propose allowing for (but not requiring) custom page titles if additional context or shortening is needed for search results. (Mostly thinking about really general pages like "Planning" which multiple guides have. As well as blog posts and case studies from eventually replatforming 18F.gsa.gov.)

Otherwise the `<title>` should be `<h1> | 18F [title from _data/titles_roots.yaml_]` 

I can look into implementing this after letting it simmer in TLC for a few days.

**Comment by MelissaBraxton** [comment]
Sounds like a sound approach to me! And you have the blessing of the content guild to boot, so I say go forth and implement.

**Comment by AnitaYCheng** [comment]
Not sure how to link the PR here (it seems to be locked for me), but [PR 57](https://github.com/18F/approaches/pull/57) takes care of this.

**Comment by AnitaYCheng** [comment]
More work needs to be done to develop the content strategy around customizing page titles. Wrote #402 to address this.

**Comment by alexbielen** [comment]
@AnitaYCheng can I close this one since we have #402 now?

**Comment by AnitaYCheng** [comment]
@alexbielen Sure!
