### ISSUE TITLE
Align with Chief of Delivery on proposed content governance plan for guides

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/TLC-crew#388]
### Meet with Andrew Dunkman to clarify roles and expectations re: ongoing maintenance of guides 
As a first step towards establishing lightweight content governance for the guides, we need to define the role of their new product owner and articulate their responsibilities. This step will inform defining the role and responsibilities of the Content Lead/Point of Contact, and their relationships to MOCHA roles.

### Point of contact on this issue
Melissa Braxton
Amelia Wong

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [X] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
One increment.

### Acceptance Criteria

- [ ] Definition of Chief of Delivery role and responsibilities is articulated and approved by acting Chief of Delivery
- [ ] Content leads have weighed in on definition and their concerns have been communicated to the Chief of Delivery and consensus has been reached.

**Comment by MelissaBraxton** [comment]
@ameliaswong  - This should be in "blocked/waiting" until @alexbielen and I meet with @adunkman on Monday 8/21. Our plan is to review the draft with him get his input and any edits before refining and finalizing.

**Comment by ameliaswong** [comment]
@MelissaBraxton and @alexbielen What shall I do with this ticket now that @adunkman is driving it forward?

**Comment by alexbielen** [comment]
@ameliaswong I think that this one is good to close. I'll close it now.
