### ISSUE TITLE
Update refreshed 18F site to USWDS 3.0

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/TLC-crew#394]
### A description of the work
The current 18F site uses USWDS version 2.14. USWDS has released version 3 last year. We should update our package to USWDS 3 to stay in sync with updates from the USWDS team and have access to the latest components. 

### Point of contact on this issue
Who can we follow-up with if we have questions?
@igorkorenfeld 

**Billable?**
- [ ] Yes
- [X] No

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
1-3 days

### Acceptance Criteria

- [ ] The refreshed site uses USWDS 3.x
- [ ] The refreshed site looks identical to how it did before the upgrade
- [ ] All links and content can still be accessed.

**Comment by MelissaBraxton** [comment]
@igorkorenfeld  - If you could make that second issue for ii. on your list, that'd be great!

**Comment by igorkorenfeld** [comment]
Done! Opened #416

**Comment by MelissaBraxton** [comment]
Looks like this has been merged! 🎉
