### ISSUE TITLE
Publish updates to "Ethics" page in UX guide(s)

### ISSUE THREAD

**Issue by AnitaYCheng** [18F/TLC-crew#396]
### A description of the work
Edit the existing [Ethics](https://ux-guide.18f.gov/research/ethics/) page with [new content](https://docs.google.com/document/d/1PTvZcXjOrbcJmwNo5UM71k78dr_NNi6nf9gcBUnyHBI/edit?usp=sharing) on the live UX guide (in Jekyll) and on the replatformed guide in Eleventy.

### Point of contact on this issue
@AnitaYCheng 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [x] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
A few hours at most.

### Acceptance Criteria

- [ ] What does "done" look like?
The [Ethics](https://ux-guide.18f.gov/research/ethics/) page on the UX Guide contains the new content in [this Google Doc](https://docs.google.com/document/d/1PTvZcXjOrbcJmwNo5UM71k78dr_NNi6nf9gcBUnyHBI/edit?usp=sharing). Make sure to tag Ron as a reviewer in the PR.

**Comment by MelissaBraxton** [comment]
We're going to hold off on this until: 
 - content governance is in place and
 - re-platformed UX guide is live.

**Comment by MelissaBraxton** [comment]
Update: 
 - content governance is unblocked! Folks picking this up will need to get PR approval from @juliaklindpaintner 
 - We can make changes on the new re-platformed UX Guide before it's launched, @alexbielen  - will help point you in the right direction where and how to make changes.

**Comment by a-chappelear** [comment]
Content updated! PR and reviewers tagged - https://github.com/18F/ux-guide/pull/423

**Comment by MelissaBraxton** [comment]
New content is now live! 🎉
