### ISSUE TITLE
Make a decision about style guide/documentation on the refreshed 18F site

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/TLC-crew#410]
### A description of the work

The current site has a [style guid section](https://18f.gsa.gov/styleguide/) that provides documentation for developing the current 18F site. The information on that page hasn't been updated in quite some time (though perhaps there was no need to do so), and some of the documentation either will not be relevant or will need updating after the refresh. We need to decide if we would like to keep the style guide and update its contents to reflect the new site, or if we want to remove it and keep relevant documentation elsewhere. To note, right now documentation about updating the site and various components is mixed between the README and the style guide. 

### Point of contact on this issue
@igorkorenfeld 

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [X] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [X] Yes
- [ ] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- [ ] We have a decision on how to proceed with the style guide and site documentaiotn

**Comment by igorkorenfeld** [comment]
Spoke with @quarterback and he is OK with either removing the style guide page if we no longer wish to use it or updating it to reflect the changes. Need to decide which strategy we wish to pursue - update the style guide or remove it and place everything in README/docs.

**Comment by igorkorenfeld** [comment]
After the conversation with Ron and working on the writing updated to the documentation, I’ve decided on the approach of depreciating the style guide pages and instead placing updated documentation in the README. 
The current version of the styleguide is outdated. Although we could update it as part of the current site update effort, as our experience with the style guide shows, keeping  the two sources of information (the style guide and the README) updated and in sync takes additional effort. It seems likely that the two would diverge again and have outdated or incomplete information. By only keeping the README we will have a single source of truth, and there would be less of a question of which to update. 

The README has the additional advantage of being easily discoverable when someone visits the github repository for our site. The same is not true of the styleguide page, as it is not part of our navigation structure, somewhat intentionally being hidden away from the more public facing pages. 
A disadvantage to this approach is that it is harder to provide a visual representation of our custom components and styles in the README. It’s still possible to do so via screenshots or links to live pages, however those screenshots and links would have to be actively maintained. However, I believe this tradeoff is worth the consistency and centralized documentation provided by the README. 
Finally I wanted to note that we can change our mind about this as we go along after the site refresh. If we realize that our needs are not met by README alone we could then add in an updated style guide page, or come up with an alternative solution

**Comment by MelissaBraxton** [comment]
Sounds good! :gavel: decision made, we can close this issue.
