### ISSUE TITLE
Add project health slackbot to DA Team Channel

### ISSUE THREAD

**Issue by colinmurphy01** [18F/TLC-crew#43]
### A description of the work

In order to get a health check on the DA Team, we'd like to consider adding [a weekly slackbot workflow](https://gsa-tts.slack.com/archives/C028GH7FA/p1677247250234159) in order to survey the team.

**Point of contact on this issue**
@annepetersen @colinmurphy01 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?

### Acceptance Criteria

- Slackbot successfully posts project health on a weekly basis (Friday at 1pm EST)
- Slackbot posts initial post + all 7 replies

**Comment by mgwalker** [comment]
Is the goal to basically pull [this Slackbot workflow](https://gsa-tts.slack.com/archives/C028GH7FA/p1677852008159969) into #18f-da-team?

**Comment by colinmurphy01** [comment]
Yes that was the proposal. However, CISA has a really good method for managing project health contributions across teammates as well ([form](https://gsa-tts.slack.com/archives/C032T4JG570/p1677772832846899) + spreadsheet). 

We should discuss this as a team, before implementing.

**Comment by mgwalker** [comment]
Oooh, I like that much better. The spreadsheet can have a summary view that would be easy for an AM to glance at, versus the Slack workflow where you'd have to look at each message in turn.

**Comment by katefisher808** [comment]
Questions I'm digging into:
- Who from the DA team is charged with submitting the aggregated data to the 18F Dashboard? How might we implement this survey to support their other tasks?
- What are the pros/cons in combining the multiple end of week reminders we have - offboarding and project health reminder?
- The base 18F dashboard survey uses language that may not be fully applicable to DA team (i.e. use of the word 'partner' and 'external blocker'). Do we want to keep it consistent for posterity?

**Comment by katefisher808** [comment]
**Survey**
https://docs.google.com/forms/d/e/1FAIpQLSfqEBHSvI5M7OihvUpaaLKXQpGvGF0LBVqHFxP_D3xHXWvsRA/viewform

**Responses** 
https://docs.google.com/spreadsheets/d/1jTjpOa1o0m9fi68XKVV0ktenAOv098LT7onniV7bdt4/edit#gid=537808

**Language for Reminder:** 
End of week reminder:
Please complete the weekly Project Health Form. Responses will be consolidated and submitted to the 18F Dashboard and also used to guide the conversation in the next retrospective.

**Comment by colinmurphy01** [comment]
I might suggest we alter the language of the COVID-19 question to reflect COVID-19 AND OTHER type stuff like OOO, illness, family stuff, etc.

**Comment by katefisher808** [comment]
Great. @abrouilette and @colinmurphy01, this ticket is ready for your review before I set up the reminder in Slack.

**Questions for you as you review:**
- What are the pros/cons in combining the multiple end of week reminders we have - offboarding and project health reminder?
- The base 18F dashboard survey uses language that may not be fully applicable to DA team (i.e. use of the word 'partner' and 'external blocker'). Do we want to keep it consistent for posterity? For now I kept the language consistent for the most part
- Do we want to allow for anonymous responses? Right now the form is not anonymous.
- Do we want to ask for a 'check' mark icon in slack for accountability? right now the language does not prompt for this.


**Survey**
https://docs.google.com/forms/d/e/1FAIpQLSfqEBHSvI5M7OihvUpaaLKXQpGvGF0LBVqHFxP_D3xHXWvsRA/viewform

**Responses (color coded by current week and past week)**
https://docs.google.com/spreadsheets/d/1jTjpOa1o0m9fi68XKVV0ktenAOv098LT7onniV7bdt4/edit#gid=537808

**Response folder in Drive**
https://drive.google.com/drive/folders/1pPqdWa4ldFcac37_IP469ZA2RMMiKtgg

**Language for Reminder, to be posted every Friday at 1pmEST:**
End of week reminder:
Please complete the weekly Project Health Form. Responses will be consolidated and submitted to the 18F Dashboard and also used to guide the conversation in the next retrospective.

**Comment by colinmurphy01** [comment]
- What are the pros/cons in combining the multiple end of week reminders we have - offboarding and project health reminder?

> Good question, my thinking is keep them separate because they serve two different audiences. Project Health is for any current team member, Offboarding is any team member leaving. But I do hear you that these auto-posts are getting unwieldy.

- The base 18F dashboard survey uses language that may not be fully applicable to DA team (i.e. use of the word 'partner' and 'external blocker'). Do we want to keep it consistent for posterity? For now I kept the language consistent for the most part

> VERY GOOD QUESTION. This might turn into a can of worms because in re-reading the descriptive copy within greens, yellows, and reds it feels kinda applicable kinda not applicable in general. Like the use of "project" feels weird and I might replace most/all mentions with "team." "Partner" doesn't feel right, per your point, maybe "product owner" or "subject matter expert?" I think external blocker is fine to keep.

- Do we want to allow for anonymous responses? Right now the form is not anonymous.

> I personally feel that submissions shouldn't be anonymous so that they can be followed up on for context and questions. However if people don't feel safe contributing with attribution, I'd favor employing anonymity to get candid feedback.

- Do we want to ask for a 'check' mark icon in slack for accountability? right now the language does not prompt for this.

> Good idea, yes.
