### ISSUE TITLE
Document what a team lead / project manager at DA does

### ISSUE THREAD

**Issue by sarahmhgov** [18F/TLC-crew#69]
**A description of the work**

Document the critical role of team lead / project manager for DA that @colinmurphy01 has currently been taking on. 

Billable?

 No
If yes, tock code:
Skills needed

Any human
 

Does this need to happen in the next two weeks?

Ideally as soon as possible, given that Colin could be assigned a project. 

How much time do you anticipate this work taking?
2-3 hr

Acceptance Criteria
- Clear description of responsibilities of a team lead/ project management role for DA. 
- Plan of action of how such a human should be assigned/ chosen and trained.

**Comment by qmanderson1** [comment]
I took a first pass at this in the doc below @sarahmhgov @colinmurphy01. Feel free to review/edit as you see fit!
[Delivery Assurance Team Lead Description & Plan of Action](https://docs.google.com/document/d/13AEVlxrDGQ5-abo8hLc4RK9JHYqwUE2JJSEMLb_jBow/edit#)

**Comment by sarahmhgov** [comment]
Yay thank you! I took the liberty of moving into review, and it's good thinking about it because Colin leaves DA in a week.

**Comment by qmanderson1** [comment]
Sounds good, thanks! @sarahmhgov  you and Colin both reviewed and I incorporated the changes so I'm going to close the issue.

**Comment by colinmurphy01** [comment]
Forgive me, I don't think I reviewed this in detail beyond the comment I was mentioned in.

Can we quickly find time to chat about it?

We should think about shipping this to [the roles and responsibilities section](https://github.com/18F/delivery-assurance/blob/main/docs/charter.md#roles-and-responsibilities) of our charter.

**Comment by qmanderson1** [comment]
No worries, @colinmurphy01 I tried to find time on our calendars this afternoon but you and @sarahmhgov are both in accessibility training. I'm out on leave starting tomorrow. I'm going to reopen the issue and you all can feel free to edit the document as needed while I'm out. Thanks for flagging this as needing some more review!
