### ISSUE TITLE
Internal hiring review process reflection

### ISSUE THREAD

**Issue by rrefoy** [18F/TLC-crew#85]
### A description of the work
Keith Wilson, head of People Ops @keithrwilson , has requested a facilitator to reflect on the internal hiring review process that has been in place the last 5 months. [Here is an overview](https://docs.google.com/document/d/11EaJO13KL7-NKMu8HwQsJS7nckPFPj5sbKcTwf9jKHc/edit) of the current process.

### Point of contact on this issue
Who can we follow-up with if we have questions? @keithrwilson 

**Billable?**

- [x] Yes
- [ ] No
If yes, tock code: 1806

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes*
- [ ] No

*I think ideally it would happen in the next three weeks but there is flexibility.

How much time do you anticipate this work taking? ~5 hours

### Acceptance Criteria

- [ ] Process reflection has been facilitated and documented. 

As the director of People Ops, I need to reflect with those participating in the hiring process about the last 5 months so that I can incorporate new learnings into the process and celebrate successes this process has already achieved.

**Comment by annepetersen** [comment]
hey Rebecca: I don't have access to the overview of the current process doc, and I suspect others would have similar issues

**Comment by rrefoy** [comment]
I've asked Keith to open this up and passed along your question.

**Comment by rrefoy** [comment]
From Keith: Someone who has at least a high level awareness of the organizational and equity challenges around internal mobility would be great, but someone with solid facilitation/retro skills more be more than acceptable

**Comment by rrefoy** [comment]
Doc should be open to all now.

**Comment by jduss4** [comment]
I can work on this!  I will reach out to @keithrwilson to chat a little about the reflection and how many people will be taking part, etc.

**Comment by jduss4** [comment]
I contacted Keith with a proposal about structure for the reflection. I am waiting to hear back about whether my proposal sounds like a good fit and scheduling. I predict that we won't get anything scheduled for another week or two at least.

**Comment by MelissaBraxton** [comment]
@jduss4  - Do you need support finding someone to take this off your plate, or would you like to see it through after you move off the team?

**Comment by jduss4** [comment]
Session 1 of the reflection was conducted!  I have also had brief conversations with multiple users of the process.  However, session 2 has been moved to May 1st due to the availability / calendar tetris considerations.  I am therefore going to move this issue to the icebox for now.  I would like to complete the task regardless of whether or not I am on the TLC crew at that time, due to having knowledge of the situation and previous reflection work.

**Comment by jduss4** [comment]
I turned this into Keith last week and he let me know that it looks good!
