### ISSUE TITLE
Create personas that represent the American public who have disabilities.  

### ISSUE THREAD

**Issue by bpdesigns** [18F/TLC-crew#92]
### A description of the work
Create personas that represent the American public who have disabilities.  

**references**
[gov.uk](http://gov.uk/) [personas](https://alphagov.github.io/accessibility-personas/) 
[Microsoft inclusive design guide](https://inclusive.microsoft.design/tools-and-activities/Inclusive101Guidebook.pdf)
(https://www.w3.org/TR/coga-usable/#appendix-mapping-user-needs-personas-and-patterns)

### Point of contact on this issue
@bpdesigns 
**Billable?**
- [ ] Yes
- [x] No

If yes, tock code:

**Skills needed**

- [x] Any human
- [x] Design
- [x] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
- 2 weeks

### Acceptance Criteria

- [x] review references above 
- [ ] determine what disabilities to include in a list of personas 
- [x] draft content
- [ ] Add link to deck from project resources Airtable

ex: As an 18F staff member who is going on parental leave, I can navigate to my
latest Tock reporting period and choose billing line #1810 by filtering by
number or "extended OOO"

**Comment by melchoyce** [comment]
Does 18F have any existing personas?

What are your hopes for this persona?

**Comment by bpdesigns** [comment]
@melchoyce great questions! Thank you. 18F does not have existing personas. Below are user stories for inspiration. I will also share this issue in the accessibility guild channel for awareness and input. 


- As an 18F team member creating a recommendations report I want to have ready made personas I can or adapt in order to help me to quickly make the case for including accessibility concerns with a partner agency.
- As an 18F team member new to designing for accessibility I can look to personas to make sure my designs and research include addressing people with different disabilities.

**Comment by annepetersen** [comment]
I could probably provide personas from some other work as idea-starters if you'd like.

**Comment by bpdesigns** [comment]
@melchoyce also ideas from @iamjolly [here](https://gsa-tts.slack.com/archives/C02BT4H5Q/p1679603308593109?thread_ts=1679602685.453009&cid=C02BT4H5Q)

**Comment by melchoyce** [comment]
Just noting I'm not claiming this issue, just hoping to get more clarity to help someone get started! Still open to anyone on the team with the expertise.

**Comment by egamble23** [comment]
Thanks much, @bpdesigns, for the clarifications! I'll review the materials and may look for a meeting time early next week. Depending on the scope, I may seek to partner with a few others on this ticket. Will take a look and go from there!

**Comment by MelissaBraxton** [comment]
@egamble23  - Are you still looking for someone to pair with on this?

**Comment by egamble23** [comment]
HI @MelissaBraxton , I'm definitely open to another person/people to pair on this! I have a start based on conversations with Ben, Kate, and Mel this week. I think this initial could benefit from additional takes/refinements, if someone has the bandwidth.

**Comment by egamble23** [comment]
@bpdesigns - Hi Ben, thanks again for the conversation on Tuesday! Here's a draft outline of two approaches based on our conversation and desk research. I took into account your feedback on making it more universal and flipping it to be more needs-based.

- The first approach takes a more storytelling approach to perhaps help spark those empathy-based conversation.
- The second one is more needs-based.

All is flexible! Just intended to be a starting point for structure of the outline. Based on your thoughts on direction, I can refine further and start building out other accessibility stories/needs. Please note further feedback will also be needed from the accessibility guild and anyone else who is interested. These can be streamlined or deepened, depending upon what would be useful for teams.

[](https://docs.google.com/presentation/d/13p84drVY-2Hi6rASiHyyaJzTU_c0MXVZosEjkjOG2_g/edit?usp=sharing)

**Comment by bpdesigns** [comment]
@egamble23 These are great! I find I'm drawn to the first approach. I think they are ready to share with g-accessibility and g-research when you are ready for broader feedback.

**Comment by egamble23** [comment]
Thanks, @bpdesigns, for your review and feedback! Much appreciated.

Just to clarify, should I be sharing the two approaches for feedback with the guilds as to which way to go for further building out personas?

Or should I start building out a few personas using the first approach for feedback/refinements of the guilds?

All good either way! Just wanted to check, thanks!

**Comment by bpdesigns** [comment]
I would recommend the 2 personas you created and adapt them so you share 2 personas in each of the approaches so folks can see the contrast between them. - Let me know if that's not clear :)

**Comment by egamble23** [comment]
Thanks, @bpdesigns ! Super helpful clarifications. 

I'll work on developing 2 personas in each of the approaches, and then I can share those for further feedback/guidance in the guilds on if there's a preferred approach for this persona ticket.

From that feedback on which approach to use, I can work on drafting a few more personas based on different accessibility needs. 

After that, these can be deepened further based on research and team needs, no worries.

**Comment by MelissaBraxton** [comment]
Hey there @bpdesigns! Erin and I chatted today and determined the deck as is is a very valuable resource partly because it demonstrates more than one approach that folks can take and adopt based on the needs of their individual project. Rather than building out additional stories or personas, we're going to call this done for now after a few next steps (below)! 

Here's the plan for wrapping this up:
 - Erin is going to post her draft deck for feedback from the accessibility guild
 - Based on their feedback, she'll include in the deck front matter a list of disabilities to prioritize creating stories for in the future, should anyone have the need on their project
 - She'll add this to the project resources Air Table so that the deck is findable for others down the road.  

Thanks for making this helpful resource a reality!

**Comment by bpdesigns** [comment]
Okay. Thanks for the update!

**Comment by MelissaBraxton** [comment]
@egamble23  - Once the deck is linked to from the project resources, Airtable, I think we can call this done!

**Comment by egamble23** [comment]
Thanks for the note, @MelissaBraxton ! I had posted it to the Accessibility Guild last Thursday for comments/refinements. I checked and I don't see further feedback, so I guess it's good to go! 

I will move a copy of the deck to the DA/TLC centralized folders and then look at adding a link to the Airtable. Will follow up!

**Comment by egamble23** [comment]
Here is the link to the file in the TLC Crew/DA team folders: https://docs.google.com/presentation/d/1EmVIzIxH2SjgNza65aaw1_xkYiWu_PzweNvb4ApnkCE/edit?usp=share_link. 

I've added a record into the Airtable as well. Thanks!
