### ISSUE TITLE
Determine what help requests in #18f-helpwanted are in-scope for DA

### ISSUE THREAD

**Issue by melchoyce** [18F/TLC-crew#95]
### A description of the work
This is a continuation of #20.

Now that we've made a new #18f-helpwanted channel and archived #microrequests, we need to determine what kinds of requests are in-scope for the DA.

See https://docs.google.com/document/d/1DgR5NPJGD6ND2xb-swNoc2XhicUwaz6y_0x6ME8a2Uw/edit#heading=h.hjozbzv1mxis for the DA's existing work into this issue.

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

**How much time do you anticipate this work taking?**

A couple hours of wrangling.

### Acceptance Criteria

- [x] We've determine what kinds of requests are and are not in scope the DA
- [x] That decision is documented

**Comment by MelissaBraxton** [comment]
Hey there @kfoley-18F  - Here's what I'm thinking for starting proposed framework for determining what kinds of help wanted requests are in scope for this group:

- **In scope (but subject to prioritization)** - Work for an 18F product, process, to support a team, or if there is an active Tock line the work can be billed to
- **Never in scope** - Non-billable, non-18F work 
- **Anything else is viewed on a case by case basis** -  (team leads will to monitor #18F-helpwanted on an ongoing basis and assess triage possible DA team work in our backlog refinement mtg and as needed for urgent requests)

I've also added to this [TLC quarterback doc](https://docs.google.com/document/d/1BM5piLtRg0q40kN7SIBZ5aNjKKBnz4H1uaN28jeLFZY/edit#) some expectations re: how and when Alex and I might monitor #18F-helpwanted and work with you to create new issues for this group as needed. 


The team's work in [this doc](https://docs.google.com/document/d/1DgR5NPJGD6ND2xb-swNoc2XhicUwaz6y_0x6ME8a2Uw/edit#heading=h.hjozbzv1mxis) was really helpful to get up to speed here! With Alex and I joining, we can bring capacity to monitor the channel. 

Once we're set on an initial criteria, we can document it [in our contributing guide](https://github.com/18F/delivery-assurance/blob/main/contributing.md)

**Comment by kfoley-18F** [comment]
Hi @MelissaBraxton - 😍 Love this!

👍 agree on the framework for #18f-helpwanted work. I can help monitor or review for that case-by-case basis. I don't anticipate that much will be super-immediately-urgent, just possibly require timely response. There may be times where the TLC doesn't have skill or capacity to help as well, so that channel is not guaranteed to provide help. 

❤️ the quarterback doc!!

What else do you need here, from me or others?

**Comment by MelissaBraxton** [comment]
Sweet! I don't think I need anything else!  I'll document this in our contributing guide before I close this out.

**Comment by MelissaBraxton** [comment]
Moving into in review, pending approval/merge of https://github.com/18F/delivery-assurance/pull/118
